### ISSUE TITLE
Add "Confirm Kill?" dialogue/step when user clicks "Kill"

### ISSUE THREAD

**Issue by spunjani** [cryoem-uoft/cryosparc-issues#100]
To prevent accidental kills.

**Comment by johnrubinstein** [comment]
I'd suggest a confirm button for all destructive actions: killing/clearing experiments, deleting experiments from the Experiments view, and removing datasets.

**Comment by mbrubake** [comment]
Along the same lines, when an experiment is running can we leave the Clear button enabled but have it both kill and clear the experiment?  Useful for when a user realizes that they screwed up the parameters or inputs or something like that.
