### ISSUE TITLE
Use named tabs for experiments/datasets to prevent tab proliferation

### ISSUE THREAD

**Issue by mbrubake** [cryoem-uoft/cryosparc-issues#103]
Currently when opening an experiment or dataset it opens in a new tab.  This can quickly lead to a large number of open tabs when navigating around.  It would be ideal if the new window was named so that if you already had that experiment open it would just switch to that tab.  Similarly, if you click back to experiments/datasets it should switch back to the experiments/datasets list.

**Comment by alipunjani** [comment]
This is dealt with in 0.2.36 (thanks Suhail) by a toggle in the user settings page where a user can decide that experiments should open in a new tab or not. By default they don't open in a new tab any more. 
But it would be nice to switch to an already open tab for experiments that are already open.. not sure how simple/possible this is in browsers. But I'll leave this open for now

**Comment by johnrubinstein** [comment]
Not sure I understand - but I like having a tab open for each experiment. Particularly useful for copying paths for outputs from the results of one experiment (structure/meta) to input of another. Also good for comparing results...

**Comment by suhaildawood** [comment]
The update in 0.2.36 introduces a setting that allows you to select whether or not experiments open in a new tab *by default*. You're still able to right click or command/ctrl click to open in a new tab.

@johnrubinstein we're working on creating a better results selector UI to allow for the selection of previous result files from within the setup process of a new experiment (#90)

Preventing duplicate tabs being opened and instead switching to an existing tab sounds more like a job for a browser extension than something we can integrate within the web app.

**Comment by mbrubake** [comment]
Actually @suhaildawood it's possible basic HTML.  (Even going back to the '90s, hence I remember it...)  The A tag has a target attribute which can be set to a unique name.  Then, if a link is clicked twice with the same target name (or two links with the same target name are clicked) it opens the links in the same window.  See http://www.w3schools.com/tags/att_a_target.asp  See also http://webdesign.about.com/cs/frameshelp/a/aaadvframes.htm specifically 

> Note: If you target a link to a frame name that doesn't exist, the browser will open a new window and give that window the specified name. After that, all anchors linked to that target will open in the new window.

**Comment by suhaildawood** [comment]
@mbrubake thanks for the suggestion - will go out in the next release.

**Comment by mbrubake** [comment]
Awesome, thanks Suhail! :)
