### ISSUE TITLE
Warp-speed kernels do not support phase shift

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#106]
Plus need to write tests.

**Comment by craigyk** [comment]
Hi Ali,

At least one of my datasets from Relion 2 (or Gctf) still inserted a phase shift column but with 0 values.  The validation code in the warp-speed refinement still flagged this as phase-plate data and exited.

**Comment by alipunjani** [comment]
Oops, sorry. Will fix that in the next release. For now the workaround will be to remove that column from your star file. Thanks for reporting the issue!

**Comment by craigyk** [comment]
No problem, easy enough.

**Comment by mbrubake** [comment]
I've implemented phase_shift support in the new kernels on a branch.  I'm going to give it some quick testing and then I'll merge.

**Comment by mbrubake** [comment]
This is now fixed (sans unit testing, but that's a bigger issue) and should roll out in the next release.
