### ISSUE TITLE
improve cache clearing heuristics?

### ISSUE THREAD

**Issue by craigyk** [cryoem-uoft/cryosparc-issues#108]
I think the cache clearing as currently implemented slows down caching Relion style datasets with lots of separate stacks because of the overhead of clearing for each file separately.  That's potentially a lot of repeated stat calls for every file in the cache on each new file transfer. 

I was wondering a quick (albeit ugly) fix for now might be to do something like clearing min(filesize*10, 1GB) to evict a little more space at a time without getting too greedy.

**Comment by johnrubinstein** [comment]
Hi Craig,
I got tired of huge Relion datasets where only a small fraction of particle images were actually used so I wrote a short program that creates a stack and starfile just for the data you need (create stack from starfile):
https://sites.google.com/site/rubinsteingroup/starfile-utilities

This could be a good fix for your situation.

**Comment by craigyk** [comment]
Cool, thanks John.

Maybe I could modify this feature request so that this functionality is integrated into CryoSparc?  Maybe caching the merged stack under a hash of the original STAR file? 

Also, I just tried implementing some of those changes, but it seems like there is some kind of code signing going on?  I had to revert, else I got a licensing error.

**Comment by spunjani** [comment]
Fixed.
