### ISSUE TITLE
"Live View" seems broken

### ISSUE THREAD

**Issue by mbrubake** [cryoem-uoft/cryosparc-issues#110]
Currently the live view doesn't appear to work any more.  No images show up, they all are broken links at the moment.  I'm not sure how much use this feature sees at the moment so this isn't very high priority.  I'd recommend we disable it for the time being unless the fix is easy.

**Comment by alipunjani** [comment]
I believe the Live View button only shows up if you're an admin user

**Comment by mbrubake** [comment]
Ahhh, ok, that's good to know.

**Comment by suhaildawood** [comment]
I'll look into differentiating experimental admin-only features to make it less confusing going forward
