### ISSUE TITLE
new experiment button should open in new tab

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#115]
If the user has their settings set to 'open experiments in new tab'

**Comment by suhaildawood** [comment]
@alipunjani, would you prefer this being a new option within settings, or coupled with the existing option?

It is quite a bit faster to set up a new experiment within the same tab as the web app doesn't need to spend time to reinitialize.

Side note: I've been brainstorming how we can more effectively handle multi-experiment management in upcoming iterations of cryoSPARC.
