### ISSUE TITLE
Improved help text for Dataset parameters

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#116]
[Dataset_parameters_text.pdf](https://github.com/cryoem-uoft/cryosparc-issues/files/669896/Dataset_parameters_text.pdf)

**Comment by johnrubinstein** [comment]
Edited .json file has been posted on slack. I suggest looking at a comparison of new and old before implementing changes (this will be particularly true for experiment-defaults-descriptions.json when I'm done with that)

**Comment by mbrubake** [comment]
I'll got through the changes now to get them committed.

**Comment by mbrubake** [comment]
Ok, I went through and committed the changes for dataset parameters.
