### ISSUE TITLE
Confusing terminology for "Ab initio heterogeneous reconstruction"

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#118]
It is confusing that the experiment type 'Ab initio heteogeneous refinement' has an option to provide "Structure inputs", "Image Metadata inputs", and "Selected Input classes".

The confusion is because the experiment type can actually be used for ab initio heterogenous reconstruction (which doesn't need these inputs) *OR* reference-based 3-D classification (which does need these inputs).

The experiment type should probably be named "Heterogeneous reconstruction" or "Ab initio or reference-based heterogeneous reconstruction" or something else...

The fields "Structure inputs", "Image Metadata inputs", and "Selected Input classes" should have text specifying that this information is not needed for ab initio heterogeneous reconstruction.

(When I did some experiments with cryosparc after these fields were introduced it didn't register that the metadata is already stored with the dataset and I tried to provide metadata even though I was planning an ab initio heterogeneous reconstruction)

**Comment by mbrubake** [comment]
Indeed, I saw that this is something that works out to be fairly confusing, particularly for new users.

I think the "Image Metadata" and "Selected Input Classes" fields should probably be grouped under a binary toggle labelled something like "Use Subset of Dataset Particles".

I don't think there is a good naming for the experiments that will be accurate, easily understood and reasonably terse.  I might suggest creating two experiment types, one labeled "Ab Initio Reconstruction" and the other named something else.  However, I suspect that the reference based 3D classification usage will ultimately move over to multi-reference refinement which @alipunjani has in progress right now.

**Comment by johnrubinstein** [comment]
For now, perhaps just modifying the "Structure inputs", "Image Metadata inputs", and "Selected Input classes" fields to remind people they are not needed if performing ab initio reconstruction.
