### ISSUE TITLE
Webapp Crash

### ISSUE THREAD

**Issue by zrip** [cryoem-uoft/cryosparc-issues#121]
Hey guys,

Recently we have seen the following error when first running refinement:

> Loading Meta file from /home/cryosparc/cryosparc/run/bulk/localhdd/sparcdata/jobs/8Hn7XnmBxuq6kPm5w/cryosparc_exp000264_final.csv ...
ERROR: No Heartbeat
This job was killed because a heartbeat was not received for 30 seconds.

> The last 100 lines of the job standard output are printed below.
====== ENVIRONMENT ========
{'CRYOSPARC_CACHE_CUSHION': '1024.0', 'MONGO_OPLOG_URL': 'mongodb://localhost:38001/local', 'CRYOSPARC_BASE_PORT': '38000', 'CRYOSPARC_MASTER_HOSTNAME': 'turing.sickkids.ca ', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'SSH_CLIENT': '172.16.26.47 55312 22', 'LOGNAME': 'cryosparc', 'SUPERVISOR_GROUP_NAME': 'webapp', 'PATH': '/home/cryosparc/cryosparc/bin:/home/cryosparc/cryosparc/anaconda2/bin:/home/cryosparc/cryosparc/mongodb/bin:/home/cryosparc/cryosparc/nodejs/bin:/usr/local/cuda-7.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'HOME': '/home/cryosparc', 'PORT': '38000', 'CRYOSPARC_DATA_DIR': '/home/cryosparc/cryosparc/run/sparcjobs', 'LANG': 'en_CA.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'en_CA:en', 'CRYOSPARC_BULK_DIR': '/home/cryosparc/cryosparc/run/bulk', 'SHLVL': '2', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'SUPERVISOR_ENABLED': '1', 'LD_LIBRARY_PATH': '/usr/local/cuda-7.5/lib64:', 'NODE_ENV': 'production', 'CRYOSPARC_DEVELOP': 'false', 'SSH_CONNECTION': '172.16.26.47 55312 172.16.26.212 22', 'CRYOSPARC_SUPERVISOR_SOCK_FILE': '/tmp/supervisor-3522675935842350195.sock', 'CRYOSPARC_INSTALL_TYPE': 'master', 'ROOT_URL': 'http://localhost:38000', 'XDG_RUNTIME_DIR': '/run/user/1003', 'CRYOSPARC_RAM_SLOTS': '4', 'CRYOSPARC_CODE_DIR': '/home/cryosparc/cryosparc/cryosparc-compute', 'HTTP_FORWARDED_COUNT': '1', 'SUPERVISOR_PROCESS_NAME': 'webapp', 'CRYOSPARC_HTTP_PORT': '38000', 'SUPERVISOR_SERVER_URL': 'unix:///tmp/supervisor-3522675935842350195.sock', 'TEST_METADATA': '{}', 'XDG_SESSION_ID': '20', '_': '/home/cryosparc/cryosparc/anaconda2/bin/supervisord', 'CRYOSPARC_MONGO_PORT': '38001', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'CRYOSPARC_CUDA_DEVS': '0', 'SSH_TTY': '/dev/pts/27', 'OLDPWD': '/home/cryosparc/cryosparc', 'APP_ID': '1ipv1tp12xzfzhba088c', 'PWD': '/home/cryosparc/cryosparc/cryosparc-webapp/bundle/programs/server', 'CRYOSPARC_ROOT_DIR': '/home/cryosparc/cryosparc', 'MAIL': '/var/mail/cryosparc', 'MONGO_URL': 'mongodb://localhost:38001/meteor', 'CRYOSPARC_UPLOAD_DIR': '/home/cryosparc/cryosparc/run/bulk/uploads', 'USER': 'cryosparc'}
===========================
(7930646002969627499354327321881480411864649530909063408480386082818703671616087049110006071474682756390395863517123085301848918903251491185589280063956661248742090598419987395347950693678507970305421552519795033814399728603807291456872685623717348614907885151064765108146199722088990482066930592060992981900764836531286397279400614338623457619035124995339540295826401617478680825340451111259652232368778583822133439978293088883506326586067998890418765067934437974763687680136596647011807075778791684786125670573519447133987134911937319978378620451331669988952423540685053256967921417407279086684146597211415729936931L,)
Fatal Python error: GC object already tracked
Segmentation fault (core dumped)

Starting the job again (without changing any parameters) runs just fine.

**Comment by zrip** [comment]
Also perhaps unrelated but we have been having webapp crashes. supervisorid.log last lines are:

> 2017-01-04 11:29:22,989 INFO spawned: 'webapp' with pid 1646
2017-01-04 11:29:24,975 INFO success: webapp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-01-04 19:39:26,840 INFO exited: webapp (exit status 1; not expected)
2017-01-05 12:46:55,279 INFO waiting for mongod to stop
2017-01-05 12:46:55,690 INFO stopped: mongod (exit status 0)
2017-01-05 12:47:01,568 INFO RPC interface 'supervisor' initialized
2017-01-05 12:47:01,568 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-01-05 12:47:01,568 INFO daemonizing the supervisord process
2017-01-05 12:47:01,569 INFO supervisord started with pid 8530
2017-01-05 12:47:01,711 INFO spawned: 'mongod' with pid 8532
2017-01-05 12:47:02,892 INFO success: mongod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-01-05 12:47:03,752 INFO spawned: 'webapp' with pid 8605
2017-01-05 12:47:04,758 INFO success: webapp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-01-05 14:46:54,651 INFO exited: webapp (exit status 1; not expected)

**Comment by alipunjani** [comment]
Hey Zev,
Thanks for reporting this, neither is something we've seen here. Does the first error happen every time, and is that with warp-speed or regular refinement?

For the second, could you send me your run/meteor.stdout file? That would have the error report from the webapp

Thanks! Hope your holidays were nice!

**Comment by zrip** [comment]
After looking through the meteor.stdout, the last few crashes seem to have come with this error

/home/cryosparc/cryosparc/cryosparc-webapp/bundle/programs/server/packages/meteor.js:786
      }).run();
         ^

RangeError: Maximum call stack size exceeded

I will also send you the file separately.

Best,
Zev

**Comment by alipunjani** [comment]
This error still happening..
```
packages/meteor.js:786
      }).run();
         ^

RangeError: Maximum call stack size exceeded
```

**Comment by alipunjani** [comment]
Temporary fix for this will be in the next version (just autorestarting the webapp if it crashes, since it's now split from the database and processing jobs)
