### ISSUE TITLE
import star file error

### ISSUE THREAD

**Issue by wjiang** [cryoem-uoft/cryosparc-issues#126]
Some valid relion star files could not be imported. Closer check of the star files led to the conclusion that rlnImageName field containing absolute path or relative path with .. in the middle of the path is not supported.

**Comment by alipunjani** [comment]
Ah. Thanks for catching this Wen. Could you post a description of the error message you get, it would help us track down where the issue might be. Thanks!

**Comment by wjiang** [comment]
Here are the error messages for a test star file in /tmp:

---- Loading File Set. Type: star Path: /net/jiang/cryosparc/run/bulk/./local_fs/tmp/x.long.star
     Loaded meta data for 19 images.
Could not find file /net/<long path to mrcs file> with base /net/jiang/cryosparc/run/bulk/./local_fs/tmp, ignoring these images...

However, it worked when I just changed the filename to start as ../net/ instead of /net for the rlnImageName field
