### ISSUE TITLE
Improving the Experiments page

### ISSUE THREAD

**Issue by wjiang** [cryoem-uoft/cryosparc-issues#128]
Two suggestions for the Experiments page:
1. enable sorting for each column
2. add a new column User for All Users mode

**Comment by suhaildawood** [comment]
Hi Wen! Thanks for your suggestions, we'll keep them in mind for future updates.

**Comment by spunjani** [comment]
#175 
#148 
#186

**Comment by spunjani** [comment]
Addressed in new version.
