### ISSUE TITLE
license does not exist

### ISSUE THREAD

**Issue by kylelmorris** [cryoem-uoft/cryosparc-issues#129]
Since upgrading to Version 0.2.47 on trying to import or execute an experiment I get the following error:

Launched job R99CEErJwDgL5uMa5
License does not exist

Should I just reinstall or is there another fix? 

$ cryosparc register --license-id=XYZ

I've never known my license number though!

**Comment by suhaildawood** [comment]
Hi Kyle, we've resolved the issue on our end. You should be able to start a new experiment now.

**Comment by kylelmorris** [comment]
Spot on, working again, thanks!

**Comment by alipunjani** [comment]
:)
