### ISSUE TITLE
nvcc fatal   : Value 'sm_61' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by kylelmorris** [cryoem-uoft/cryosparc-issues#130]
Getting the error in the subject now for running ab initio. Presuming this is related to having CUDA 8.0 installed. Can anyone clarify?

**Comment by alipunjani** [comment]
Hi Kyle,

Thanks for reporting. Did you recently upgrade to CUDA8.0 and a more recent GPU? This error happens when cryosparc was installed using an older version of CUDA and an older GPU. 
To fix this, try:

```
eval $(cryosparc env)
echo $PATH
echo $LD_LIBRARY_PATH
```
Now check to ensure that the correct cuda location (usually /usr/local/cuda/bin and /usr/local/cuda/lib64) are in the PATH and LD_LIBRARY_PATH. If not, you need to edit the `cryosparc/config.sh` file to change the paths stored there to point to CUDA 8.0. Then, in the same terminal shell, do
```
pip uninstall pycuda
pip install pycuda --no-cache-dir
```
This will force re-installation and re-compilation of PyCUDA against CUDA8.0, and then everything should work.

Let me know if any trouble,
Ali

**Comment by kylelmorris** [comment]
Hi Ali,

CUDA 8 was on here before and all was well. Checking what cryosparc is compiled against along with PATH and LD_LIBRARY_PATH seems to suggest this is ok and compiled against cuda 8. I did however recently add an additional GPU, of the same model as the existing GPU’s, perhaps this upset something.

I updated the config.sh to reflect that there are four GPU’s, before it was CRYOSPARC_CUDA_DEVS=“0,1,2”, changed to be “0,1,2,3”. Then reinstalled pycuda as you suggest.

Runs without a hitch now.

Thanks for you help!!

Best wishes,
Kyle

**Comment by alipunjani** [comment]
Great! That is strange considering the new GPU was the same model. 
By the way, you can modify the GPU list using
```
cryosparc configure gpu list
cryosparc configure gpu enable <id>
cryosparc configure gpu disable <id>
```

**Comment by maxewilkinson** [comment]
Hi Ali,

I'm getting the same error message when running either ab initio reconstruction or refinement. Reinstalling pycuda did not help.
I am using CUDA 7.5, which is referenced correctly in echo $PATH. I'm also using one GPU only, which is reflected correctly in CRYOSPARC_CUDA_DEVS="0"
You mentioned above that there should be a path to cuda in cryosparc/config.sh but I cannot find this path.

Any ideas?

Cheers,
Max

**Comment by alipunjani** [comment]
Hi Max, thanks for reporting. 
My current understanding is that for newer GPUs (Titan X, 1080/1070, etc), even though other programs have worked using CUDA7.5, cryoSPARC does require CUDA8.0 right now. There may be a workaround in the future that will allow use with older cuda versions, but we don't know how to do that yet. Fortunately CUDA8.0 is stable so hopefully it won't be too much trouble for you to upgrade.
If you end up keeping both CUDA7.5 and CUDA8.0 then you can specifically tell cryoSPARC to use CUDA8.0 by adding the lines to the top of `config.sh`:
```
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$PATH
```
The reason that you don't see them in `config.sh` right now is that our installer only puts them in if `nvcc` wasn't already in your PATH at the time of installation.

Once you change the config.sh file, you will need to 
```
cryosparc stop
eval $(cryosparc env)
pip uninstall pycuda
pip install pycuda --no-cache-dir
```

Hope this helps,
Ali

**Comment by maxewilkinson** [comment]
Hi Ali,
Thanks a lot - installing CUDA8.0 did the trick after I modified the config.sh and removed CUDA7.5 from $PATH before reinstalling pycuda. The programme works perfectly now

**Comment by alipunjani** [comment]
@maxewilkinson great!
