### ISSUE TITLE
CUDA version issues

### ISSUE THREAD

**Issue by martinsingleton** [cryoem-uoft/cryosparc-issues#131]
As in the previous issue, I see:

nvcc fatal : Value 'sm_61' is not defined for option 'cpu-architecture'

The install was against Cuda 7.5, on a machine with a GTX1080 and Quadro M6000. If I disable the GTX108 and try and re-run with just the Quadro, I see:

ExecError: error invoking 'nvcc --preprocess -arch sm_52 -I/software/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda /tmp/tmpUI_Ndf.cu --compiler-options -P': [Errno 2] No such file or directory

**Comment by alipunjani** [comment]
Hi Martin,

Thanks for reporting this issue. The GTX1080 does require CUDA8.0, which explains the first error. CUDA 8.0 is now stable, so it's probably a good idea to install it. 
The second error, with only the M6000 enabled, seems to be something to do with your $PATH.. is it possible that you may have installed cryosparc using sudo? Can you run the command `cryosparc status` and report the result?

Sorry for the trouble, hopefully we can sort it out quickly.

Thanks,
Ali

**Comment by mbrubake** [comment]
The first error can be resolved by installing CUDA8.0 which will give the best performance.  However, it should still be possible to use CUDA7.5 by giving nvcc an earlier compute capability.  This is actually an issue with PyCUDA where it will always request nvcc to use the max compute capability of the device regardless of whether the CUDA version supports it.  This issue will likely come up every time NVIDIA releases a new generation of cards.  I'm looking into a fix for it now.

**Comment by martinsingleton** [comment]
Thanks for the information.  I did think that 7.5 on the GTX1080 might be the problem, although some other software does seem to run with this combination. But I’ll upgrade to 8.0. Does Cryosparc need to be re-installed with nvcc and LD_LIBRARY path set for the the new Cuda version, or can I simple change the environment variable now? For the second point, the install was not as root.

export CRYOSPARC_ROOT_DIR="/software/cryosparc"
export CRYOSPARC_LICENSE_ID=XXXXXXXXXXXXXXXXXXXX
export CRYOSPARC_REGISTER_DONE=true
export CRYOSPARC_METEOR_BINDIR=""
export CRYOSPARC_NODEJS_BINDIR="/software/cryosparc/nodejs/bin"
export CRYOSPARC_MONGODB_BINDIR="/software/cryosparc/mongodb/bin"
export CRYOSPARC_ANACONDA_BINDIR="/software/cryosparc/anaconda2/bin"
export CRYOSPARC_HTTP_PORT=38000
export CRYOSPARC_MONGO_PORT=38001
export CRYOSPARC_MASTER_HOSTNAME=XXXXXXXXXXXXXXXXXX
export CRYOSPARC_INSTALL_TYPE=master
export CRYOSPARC_DEVELOP=false
export METEOR_SETTINGS="{\"public\":{\"webinstance\":false, \"instancename\":\"XXXXXXXXXXXXX\", \"instancetype\":\"academicbeta\"}}"
export CRYOSPARC_SUPERVISOR_SOCK_FILE=/tmp/supervisor-2541968549080917360.sock

export CRYOSPARC_CACHE_CUSHION=10240.0
export CRYOSPARC_RAM_SLOTS="16"
export CRYOSPARC_CUDA_DEVS="1"

**Comment by alipunjani** [comment]
Thanks @mbrubake, @martinsingleton.
It would be best to re-install cryosparc after installing CUDA8.0 and setting the environment variables. 
I'm not sure what the M6000 issue is. Are you running on Ubuntu? The `No such file or directory` error I've seen before when the PATH is not set at the time of launching cryoSPARC (i.e. `cryosparc start`), but the installer would have complained if nvcc wasn't in the PATH at install time. Perhaps you can double-check the PATH and LD_LIBRARY_PATH right before `cryosparc start`?

**Comment by martinsingleton** [comment]
Re-install with CUDA8.0 has fixed it. Thanks for your help.
