### ISSUE TITLE
"Unknown error" when trying to Visualize or launch any jobs

### ISSUE THREAD

**Issue by andreymalg** [cryoem-uoft/cryosparc-issues#133]
I see "An unknown error occurred." when trying to Visualize or run experiments. The error is not terribly descriptive to help in troubleshooting. CryoSparc was installed on OpenSuse 13.2. The only issue during installation is show below.
"Install npm packages

npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.6.2 (node-v46 ABI) (falling back to source compile with node-gyp) 
"
Any help will be greatly appreciated

Andrey

**Comment by alipunjani** [comment]
Hi Andrey, 
Thanks for reporting - this is an issue that a few users have reported on some operating systems (we only test on Ubuntu and CentOS/RHEL). We're trying to debug it, can you tell me your gcc/c++ versions:
`gcc --version`
`g++ --version`

**Comment by andreymalg** [comment]
Hi Ali,
gcc and g++ show the same version output: 
gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064].

Andrey

**Comment by alipunjani** [comment]
In cryosparc, was the error reported inside the results view? Can you paste the entire traceback? 

Also can you run the command
`cryosparc env`
and tell me the output?

**Comment by alipunjani** [comment]
And one more thing: In the visualize job that failed, is the first line of output something that looks like this:
`Launched job QSb9Lc6BcbSRqGBWR`
If so, can you take the ID from there and look for a folder inside the cryosparc installation directory, the path will be 
`cryosparc/run/sparcjobs/<ID>`
inside that folder there is a file called `stdout` can you paste the contents?

**Comment by andreymalg** [comment]
`cryosparc env` outputs:
 export PATH="/data/Andrey/SoftWare/CryoSparc_v2/mongodb/bin:/data/Andrey/SoftWare/CryoSparc_v2/nodejs/bin:/data/Andrey/SoftWare/CryoSparc_v2/anaconda2/bin:/data/Andrey/SoftWare/CryoSparc_v2/bin:/data/Andrey/SoftWare/OpenMPI/openmpi-1.10.3/bin:/data/Andrey/SoftWare/Cuda-7.5/bin:/guam.raid.cluster.software/Latex/bin/x86_64-linux/:/bin:/usr/bin:/data/Andrey/SoftWare/GCTF/Gctf_v0.50/bin/:/data/Andrey/SoftWare/Gautomatch/Gautomatch_v0.53/bin/:/guam.raid.cluster.software/gnuplot-4.6.6/bin/";
export 
 LD_LIBRARY_PATH="/data/Andrey/SoftWare/OpenMPI/openmpi-1.10.3/lib64:/data/Andrey/SoftWare/Cuda-7.5/lib64:/usr/lib64:/usr/lib:/usr/lib/X11:/usr/X11R6/lib:/usr/local/lib:/programs/x86_64-linux/lib32:/guam.raid.cluster.software/gnuplot-4.6.6/lib:/data/Andrey/SoftWare/Libraries/"

Going to Visualize and hitting Launch results in:
" Launched job ####
 An unknown error occurred."
The stdout for one such job contains:

> ====== ENVIRONMENT ========
{'LESS': '-M -I -R', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-mWbp2oXjVC,guid=02c6956d44c60466c6c69850589b57df', 'XKEYSYMDB': '/usr/X11R6/lib/X11/XKeysymDB', 'KDE_FULL_SESSION': 
'true', 'PROFILEHOME': '', 'SHELL': '/bin/bash', 'COLORFGBG': '15;0', 'CRYOSPARC_BULK_DIR': '/data/Andrey/SoftWare/CryoSparc_v2/run/bulk', 'XDG_DATA_DIRS': '/usr/share:/usr/share', 'XDG_SESS
ION_ID': '1', 'SUPERVISOR_ENABLED': '1', 'HISTSIZE': '1000', 'TEST_METADATA': '{}', 'LESS_ADVANCED_PREPROCESSOR': 'no', 'MANPATH': '/usr/lib64/mpi/gcc/openmpi/share/man:/usr/local/man:/usr/s
hare/man', 'XMODIFIERS':  @im=local', 'JAVA_HOME': '/usr/lib64/jvm/jre', 'PROFILEREAD': 'true', 'XDG_RUNTIME_DIR': '/run/user/1041', 'KONSOLE_DBUS_SERVICE': ':1.70', 'CRYOSPARC_REGISTER_DONE
': 'true', 'CRYOSPARC_METEOR_BINDIR': '', 'GS_LIB': '/home/agmalyut/.fonts', 'SHELL_SESSION_ID': 'd9698181e4c64000ac050a8d24e28439', 'DESKTOP_SESSION': 'default', 'CONFIG_SITE': '/usr/share/
site/x86_64-unknown-linux-gnu', 'GTK_MODULES': 'canberra-gtk-module', 'HOSTNAME': 'estr', 'CRYOSPARC_NODEJS_BINDIR': '/data/Andrey/SoftWare/CryoSparc_v2/nodejs/bin', 'MAIL': '/var/spool/mail
/agmalyut', 'MONGO_URL': 'mongodb://localhost:38001/meteor', 'SSH_ASKPASS': '/usr/lib/ssh/ksshaskpass', 'MONGO_OPLOG_URL': 'mongodb://localhost:38001/local', 'JAVA_ROOT': '/usr/lib64/jvm/jre
', 'CRYOSPARC_MASTER_HOSTNAME': 'estr.cpmc.columbia.edu', 'MINICOM': '-c on', 'CSHEDIT': 'emacs', 'LESSOPEN': 'lessopen.sh %s', 'MACHTYPE': 'x86_64-suse-linux', 'SUPERVISOR_GROUP_NAME': 'web
app', 'INPUTRC': '/home/agmalyut/.inputrc', 'XDG_VTNR': '7', 'DM_CONTROL': '/var/run/xdmctl', 'PORT': '38000', 'CRYOSPARC_DATA_DIR': '/data/Andrey/SoftWare/CryoSparc_v2/run/sparcjobs', 'SUPE
RVISOR_SERVER_URL': 'unix:///tmp/supervisor-1929299466586048315.sock', 'LANGUAGE': '', 'SESSION_MANAGER': 'local/estr:@/tmp/.ICE-unix/1818,unix/estr:/tmp/.ICE-unix/1818', 'SHLVL': '4', 'ALSA
_CONFIG_PATH': '/etc/alsa-pulse.conf', 'CPU': 'x86_64', 'NODE_ENV': 'production', 'CRYOSPARC_DEVELOP': 'false', 'WINDOWID': '92274714', 'KONSOLE_DBUS_SESSION': '/Sessions/7', 'QT_IM_SWITCHER
': 'imsw-multi', 'ROOT_URL': 'http://localhost:38000', 'KDE_SESSION_UID': '1041', 'JAVA_BINDIR': '/usr/lib64/jvm/jre/bin', 'QT_PLUGIN_PATH': '/guam.raid.home/agmalyut/.kde4/lib64/kde4/plugin
s/:/usr/lib64/kde4/plugins/', 'CRYOSPARC_RAM_SLOTS': '4', 'SUPERVISOR_PROCESS_NAME': 'webapp', 'CRYOSPARC_HTTP_PORT': '38000', 'XSESSION_IS_UP': 'yes', 'GTK2_RC_FILES': '/etc/gtk-2.0/gtkrc:/
home/agmalyut/.gtkrc-2.0:/guam.raid.home/agmalyut/.kde4/share/config/gtkrc-2.0', 'LS_OPTIONS': '-N --color=tty -T 0', 'XNLSPATH': '/usr/share/X11/nls', '_': '/data/Andrey/SoftWare/CryoSparc_
v2/anaconda2/bin/python', 'GTK_IM_MODULE': 'cedilla', 'LS_COLORS': 'no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01
;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=0
0;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=0
1;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=0
0;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:', 'XDG_CONFIG_DIRS': '/etc/xdg', 'OMP_NUM_THREADS': '1', 'WINDOWMANAGER': '/usr/bin/startkde', 'CRYOSPARC_LICENSE_ID': '23b9ae27-dc3d-5ae6-ad0e-41fc
24857465', 'CRYOSPARC_ROOT_DIR': '/data/Andrey/SoftWare/CryoSparc_v2', 'GTK_RC_FILES': '/etc/gtk/gtkrc:/home/agmalyut/.gtkrc:/guam.raid.home/agmalyut/.kde4/share/config/gtkrc', 'QEMU_AUDIO_D
RV': 'pa', 'MORE': '-sl', 'PAGER': 'less', 'CRYOSPARC_UPLOAD_DIR': '/data/Andrey/SoftWare/CryoSparc_v2/run/bulk/uploads', 'KDE_MULTIHEAD': 'false', 'CRYOSPARC_CACHE_CUSHION': '10240.0', 'QT_
**SYSTEM_DIR': '/usr/share/desktop-data', 'HOME': '/home/agmalyut', 'LD_LIBRARY_fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)**.
PATH': '/data/Andrey/SoftWare/OpenMPI/openmpi-1.10.3/lib64:/data/Andrey/SoftWare/Cuda-7.5/lib64:/usr/lib64:/usr/lib:/usr/lib/X11:/usr/X11R6/lib:/usr/local/lib:/programs/x86_64-linux/lib32:/g
uam.raid.cluster.software/gnuplot-4.6.6/lib:/data/Andrey/SoftWare/Libraries/', 'LANG': 'en_US.UTF-8', 'G_BROKEN_FILENAMES': '1', 'TMPDIR': '/tmp', 'OSTYPE': 'linux', 'MKL_NUM_THREADS': '1', 
'NNTPSERVER': 'news', 'CRYOSPARC_CODE_DIR': '/data/Andrey/SoftWare/CryoSparc_v2/cryosparc-compute', 'HTTP_FORWARDED_COUNT': '1', 'G_FILENAME_ENCODING': '@locale,UTF-8,ISO-8859-15,CP1252', 'H
OST': 'estr', 'CRYOSPARC_ANACONDA_BINDIR': '/data/Andrey/SoftWare/CryoSparc_v2/anaconda2/bin', 'GPG_TTY': '/dev/pts/7', 'CRYOSPARC_MONGO_PORT': '38001', 'FROM_HEADER': '', 'LESSCLOSE': 'less
close.sh %s %s', 'USE_FAM': '', 'CRYOSPARC_CUDA_DEVS': '0,1', 'CVS_RSH': 'ssh', 'JRE_HOME': '/usr/lib64/jvm/jre', 'USER': 'agmalyut', 'XDG_CURRENT_DESKTOP': 'KDE', 'HOSTTYPE': 'x86_64', 'NUM
EXPR_NUM_THREADS': '1', 'QT_IM_MODULE': 'xim', 'LOGNAME': 'agmalyut', 'XDG_SEAT': 'seat0', 'PATH': '/data/Andrey/SoftWare/CryoSparc_v2/mongodb/bin:/data/Andrey/SoftWare/CryoSparc_v2/nodejs/b
in:/data/Andrey/SoftWare/CryoSparc_v2/anaconda2/bin:/data/Andrey/SoftWare/CryoSparc_v2/bin:/data/Andrey/SoftWare/OpenMPI/openmpi-1.10.3/bin:/data/Andrey/SoftWare/Cuda-7.5/bin:/guam.raid.clus
ter.software/Latex/bin/x86_64-linux/:/bin:/usr/bin:/data/Andrey/SoftWare/GCTF/Gctf_v0.50/bin/:/data/Andrey/SoftWare/Gautomatch/Gautomatch_v0.53/bin/:/guam.raid.cluster.software/gnuplot-4.6.6
/bin/', 'KDE_SESSION_VERSION': '4', 'SSH_AGENT_PID': '1742', 'TERM': 'xterm', 'KONSOLE_PROFILE_NAME': 'Shell', 'SDL_AUDIODRIVER': 'pulse', 'WINDOWPATH': '7', 'METEOR_SETTINGS': '{"public":{"
webinstance":false, "instancename":"estr.cpmc.columbia.edu", "instancetype":"academicbeta"}}', 'CRYOSPARC_SUPERVISOR_SOCK_FILE': '/tmp/supervisor-1929299466586048315.sock', 'CRYOSPARC_INSTAL
L_TYPE': 'master', 'CRYOSPARC_MONGODB_BINDIR': '/data/Andrey/SoftWare/CryoSparc_v2/mongodb/bin', 'COLORTERM': '1', 'SSH_AUTH_SOCK': '/tmp/ssh-UdX2zqZFv75F/agent.1639', 'XDM_MANAGED': 'method
=classic', 'LESSKEY': '/etc/lesskey.bin', 'XCURSOR_THEME': 'DMZ', 'LSCOLORS': 'ExFxCxDxBxegedabagacad', 'DISPLAY': ':0', 'AUDIODRIVER': 'pulseaudio', 'PYTHONSTARTUP': '/etc/pythonstart', 'AP
P_ID': '1ipv1tp12xzfzhba088c', 'CLICOLOR': '1', 'PWD': '/data/Andrey/SoftWare/CryoSparc_v2/cryosparc-webapp/bundle/programs/server', 'XAUTHLOCALHOSTNAME': 'estr'}
===========================

**Comment by alipunjani** [comment]
Thanks Andrey. After some digging I believe the problem is that on OpenSUSE, the `ifconfig` utility (used in cryoSPARC for reporting license status to our servers) is not in a normal user's `PATH`. Can you please try the following (as the user running cryosparc):
`ln -s /sbin/ifconfig ~/bin/`
then verify ifconfig is okay with
```
which ifconfig
ifconfig
```
Then you can re-start cryosparc:
`cryosparc stop`
`cryosparc start`

Please let us know if this works.
Thanks,
Ali

**Comment by andreymalg** [comment]
Hi Ali,

Adding ifconfig to the path has solved the issue. I was able to Visualize particles and to submit a refinement job.  Thank you for your help!

Andrey

**Comment by alipunjani** [comment]
No problem! Glad it worked out.
