### ISSUE TITLE
Numpy > 1.11 gives error when reading csv files for subclasses

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#134]
In sparcjob.py:207, numpy no longer allows automatic conversion of a ndim>0 array to a scalar for indexing a python list (why?!). 

Temporary fix:
```
eval $(cryosparc env)
conda install -q -y numpy=1.11.2
```

**Comment by spunjani** [comment]
Closing as fixed in new version.
