### ISSUE TITLE
Error during AbInitio run

### ISSUE THREAD

**Issue by RezaKhayat** [cryoem-uoft/cryosparc-issues#136]
Hi,
I'm getting the following error:

Launched job KDGTxJHfpo9p3wm63

License is valid.

Job Type:  abinit  Job ID:  KDGTxJHfpo9p3wm63

Assigned Slots: RAM:  [0]  GPU:  [0]

Starting Ab-Initio Reconstruction, Experiment ID  Hxbky6egggTwPp5bo

Traceback (most recent call last):
  File "/mnt/Data_01/cryosparc/cryosparc-compute/sparcjob.py", line 109, in <module>
    datasetdoc = MongoLinkedDict(datasetcol, expdoc['dataset_id'])
  File "/mnt/Data_01/cryosparc/cryosparc-compute/sparc/util.py", line 24, in __init__
    self.fetch()
  File "/mnt/Data_01/cryosparc/cryosparc-compute/sparc/util.py", line 26, in fetch
    dict.update(self, self.collection.find_one({'_id':self._id}))
TypeError: 'NoneType' object is not iterable

The system has 4 Gigabyte 1070 Founder Edition cards with CUDA 8.0 installed. These were installed prior to the installation of cryosparc. Any suggestions would be appreciated.

**Comment by alipunjani** [comment]
Hi Reza,

Thanks for reporting - can you please run the command 
`cryosparc status`
and report the output? It looks like the database might be down for some reason.

Ali

**Comment by RezaKhayat** [comment]
Hi Ali,

I thought the problem may be because I installed cryosparc with gcc-5.2.0 (rather than the suggested 4.9). So I deleted cryosparc, installed gcc-4.9.0, and installed cryosparc. Cryosparc is now working. Unfortunately, I can't help identify what the problem may have been.

Reza

**Comment by alipunjani** [comment]
Ah - nice job figuring it out! Thanks for letting us know.
