### ISSUE TITLE
license expired?

### ISSUE THREAD

**Issue by ekellogg** [cryoem-uoft/cryosparc-issues#137]
Hi Ali, 

I just tried uploading a new dataset after a hiatus using cryosparc, and it says 
'license expired on Wednesday November 30 2016'
how do I resolve this issue? Thanks!

Liz

**Comment by alipunjani** [comment]
Hi Liz,

Which version of cryoSPARC are you running? We had expired the old version to make sure people aren't running into bugs we've fixed. If you update to the latest version (via the button on the dashboard) then I believe everything should work (but let me know if it doesn't).

Ali

**Comment by ekellogg** [comment]
Hi Ali,

we just updated to version 0.2.47, and now the error is:

Could not find license ID. Please contact register@structura.bio to obtain one.

is this an error on your end? can you help us out with the licensing?
 Thanks for your quick response.

Liz

**Comment by alipunjani** [comment]
Hi Liz,
I'm creating a new license ID for you - will email you in just a sec
Ali

**Comment by ekellogg** [comment]
nice, thank you!!

**Comment by alipunjani** [comment]
No problem - let me know

**Comment by wliu8** [comment]
Hi Cryosparc developers,

We are running into a "license expired" issue.  The error message is shown below:
![image](https://cloud.githubusercontent.com/assets/26014237/23814955/aa4152ac-05b3-11e7-9af0-b5307de755e7.png)
We can't run anything at the moment. 

I read through these comments above.  It seems that we need to update our current version (0.3.2).  Is this correct?  Where can we upload the latest version and the license file? 

Thank you very much for your kind help!

Best,
Weili

**Comment by wliu8** [comment]
Hi Developers,

Here is the error message: "Error connecting to cryoSPARC license server. Checking local license file. Local license file is expired. Please re-establish your connection to the license servers".  

![image](https://cloud.githubusercontent.com/assets/26014237/23815185/efeda2aa-05b4-11e7-8fd6-e800dcc25ed3.png)

Could you please let us know how to best resolve this "expired" license issue.  

Best,
Weili

**Comment by alipunjani** [comment]
Hi Weili,

Is your cryoSPARC machine connected to the internet?
Our license systems are all running fine and your license is not expired (academic licenses don't expire), but the error indicates that your machine hasn't been able to connect to our servers for at least 1 week (which is probably why you haven't seen the update for version 0.3.6 which would have shown right on the dashboard with a button to click to update).
Can you make sure the machine can reach our servers? After ssh'ing in, try:
```
ping activate.cryosparc.com
```

Please let me know what happens.
Thanks,
Ali

**Comment by wliu8** [comment]
Hi Ali,

Our cryoSPARC machine is actually a GPU node under our cluster system.  Our computer specialist who set up cryosparc said that the node is able to reach internet.  Before this "expired" license issue occurred, I could see and click on the "update" button for version 0.3.6.  After I clicked this update, when I tried to run a new experiment, the license became an issue. After that, I even couldn't connect to the cryosparc GUI.  We have been trying to trouble shoot from our end. That is why you didn't see the connection to your servers.  

I will forward your instruction to our specialist and see if he can reach your servers.  I will let you know.  Thank you so much!

Best,
Weili

**Comment by wliu8** [comment]
Hi Ali,

Adam (our specialist) tested.  Here is his response and the output. 
![image](https://cloud.githubusercontent.com/assets/26014237/23817491/83da902a-05c1-11e7-94b3-618af6215e4e.png)
![screen shot 2017-03-10 at 6 44 22 pm](https://cloud.githubusercontent.com/assets/26014237/23817522/b240137c-05c1-11e7-91f3-277340783121.png)

Thank you so much for solving this puzzle...

Best,
Weili
