### ISSUE TITLE
Build issue on CentOS 7.2

### ISSUE THREAD

**Issue by jucastil** [cryoem-uoft/cryosparc-issues#139]
Hello,

This is practically a copy of the build issue #138

When I try to re-install cryosparc, i get the following errors when it prompts me for the output directory, then the whole installation crashes. 

The previous version (v0.2.47) was working without problems. 
I moved the license before the reinstallation.

If you need more details about my system, please let me know.

 Enter path (tab-completion is enabled) 
  : "/home/XXXX/cryo_out"
Error: path does not exist. Retry.
  : /home/XXXX/cryo_out
  The default output directory has been set.
Traceback (most recent call last):
  File "/home/XXXX/cryo/bin/configure.py", line 80, in <module>
    trycall(["cryosparc", "configure", "bulk", "add", uploadpath, 'uploads'])
  File "/home/XXXX/cryo/bin/util.py", line 8, in trycall
    ret = subprocess.check_output(cmds, **kwargs)
  File "/home/XXXX/cryo/anaconda2/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/XXXX/cryo/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/XXXX/cryo/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

Best regards,

Juan

**Comment by alipunjani** [comment]
Thanks for reporting Juan - I may have broken something in the update to version 0.3. Looking into it now

Ali

**Comment by alipunjani** [comment]
So just to clarify, you had 0.2.47 working on one machine, you updated that and it was fine, then you deactivated it and tried to reinstall 0.3 on another machine and had this error?

**Comment by jucastil** [comment]
Yes. That is correct. Both machines are having the same system (CentOS.7.2). Both have also the same kernel, but they may differ on some packages. If I can comment on it, it looks like a casting error (it gets something else than a string, maybe a zero? )

**Comment by alipunjani** [comment]
Yeah it was a silly mistake on my part - i'm just testing the fix and I'll deploy a new version in a couple mins

**Comment by jucastil** [comment]
Super! 
I will try again in a couple of hours. 
I will let you know when I have it back working, and close the issue. 
Thank you for the quick answer!

**Comment by alipunjani** [comment]
Great, definitely let me know. I just deployed v0.3.1 with the fix. If you just try installing again it should work.
Glad to help! :)

**Comment by jucastil** [comment]
It seems to work so far. Closing the issue! Great job :+1:
