### ISSUE TITLE
Refinement cuMemAlloc failed

### ISSUE THREAD

**Issue by jhm13c** [cryoem-uoft/cryosparc-issues#142]
Hi,

I was in the process of doing a refinement but I always end up with this error,

> Traceback (most recent call last):
  File "/home/joshua/cryosparc/cryosparc-compute/sparcjob.py", line 299, in <module>
    superspeed = job_type=='superrefine')
  File "/home/joshua/cryosparc/cryosparc-compute/refinement.py", line 152, in refine
    align_R,align_t = alignment.align_symmetry(initmodel,symop)
  File "/home/joshua/cryosparc/cryosparc-compute/alignment.py", line 203, in align_symmetry
    gpuarray.to_gpu(n.copy(fV.imag).astype(n.float32)))
  File "/home/joshua/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 975, in to_gpu
    result = GPUArray(ary.shape, ary.dtype, allocator, strides=_compact_strides(ary))
  File "/home/joshua/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory

My guess is the GPU memory is not sufficient, but I am not sure if this is correct and if there is a way to work around it.

- I have 2 GeForce GTX Titan Black, each of them has 6GB of memory .
- Dataset image size is 1024
- Using a total of 1 classes and 7306 particles
- The error occurs right after, Aligning initial model to symmetry.

**Comment by alipunjani** [comment]
Hi, the problem is your box size: by default cryosparc refinement will use the image size (1024) as the box size of refinement volumes, but this is way too large for a 6GB GPU (or any currently available GPU actually). You can specify a refinement box size in the parameters of your refinement experiment before you launch it. Depending on the physical size of your particle you can set this to a reasonable value.

Hope that helps,
Ali

**Comment by jhm13c** [comment]
Hi,

Thank you for the quick response. Unfortunately that didn't help. I tried adjusting the refinement box size to different values (512, 256, 128) but none of them worked, it gave me the same error.

**Comment by mbrubake** [comment]
I just checked and if the memory limit is getting hit during symmetry alignment then changing the box size parameter won't help.  That's mostly an oversight on our part though.  I'll see if I can push a change for that.
