### ISSUE TITLE
Sharpen tool broken (results_input)

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#144]
From Anthony:

Hi Ali,

I have been playing around with cryoSPARC using some EMPIAR datasets, and I'm quite impressed with the program. Today, I used the shiny particle stack from EMPIAR-10081 and got down to 3.5A, the same resolution reported in publication.

However, I ran into some issues sharpening the map, and got the following error :

 Launched job TxzqoNCPgEocTE5FD

License is valid.

Job Type:  sharpen  Job ID:  TxzqoNCPgEocTE5FD

Assigned Slots: RAM:  []  GPU:  []

Loading Inputs...

Traceback (most recent call last):
  File "/home/amedee/bin/cryoSPARC/cryosparc-compute/sparcjob.py", line 372, in <module>
    input_result_doc = MongoLinkedDict(mongo_results_collection, (input_result['result_id']))
NameError: name 'input_result' is not defined

Was it something i did?

**Comment by jhm13c** [comment]
I ran into this problem as well. But I didn't know if it was something I did.

Joshua

**Comment by alipunjani** [comment]
No this is definitely a bug on our side - will fix in the next release.
Ali

**Comment by alipunjani** [comment]
Fixed - will be deployed in next release.
