### ISSUE TITLE
File format transform: From .csv to .star, which can be used in relion1.4 or relion2.0

### ISSUE THREAD

**Issue by xdic** [cryoem-uoft/cryosparc-issues#145]
Is there some function module or script that can transform the .csv file to .star file, which can be used in relion?  Thank you very much!

**Comment by mbrubake** [comment]
See this thread https://discuss.cryosparc.com/t/export-star-file/48 for info on a script to do this that you can use now.

**Comment by xdic** [comment]
that is great, thank you!
