### ISSUE TITLE
Sharpen job fails in v0.3.2beta

### ISSUE THREAD

**Issue by DHouldershaw** [cryoem-uoft/cryosparc-issues#146]
Hi, 
Running v0.3.2beta, the 'Sharpen' experiment job fails with the error:
```
Launched job CQzrLmPGZSGwhmZ4d
License is valid.
Job Type:  sharpen  Job ID:  CQzrLmPGZSGwhmZ4d
Assigned Slots: RAM:  []  GPU:  []
Loading Inputs...
Traceback (most recent call last):
  File "/opt/cryosparc/cryosparc-compute/sparcjob.py", line 372, in <module>
    input_result_doc = MongoLinkedDict(mongo_results_collection, (input_result['result_id']))
NameError: name 'input_result' is not defined
```
from looking at sparcjob.py it looks like `input_result['result_id']` should be `input_results['result_id']` ??

**Comment by Kapick** [comment]
Same here. 
Just did a wipe and fresh install of Version 0.3.2. Same problem and error output.
Used to work in the original beta release.

--
Mike

**Comment by jhm13c** [comment]
I ran into the same problem. It appears that is a problem from there side, and it will be fixed on the next released.
