### ISSUE TITLE
Ab-initio with 10 classes crash

### ISSUE THREAD

**Issue by Kapick** [cryoem-uoft/cryosparc-issues#147]
Hi all,

Running an ab-initio reconstruction with 10 classes and all default settings. Happened with two different datasets in the same manner. Smaller classes became completely depopulated and then crashed.

---------------------data_dump------------------
Done iteration 00630 of 01290 in 26.041s. Total time 17336.2s. Est time remaining 19988.8s.
----------- Iteration   631 (epoch 1.477).  radwn 27.24  resolution 11.10A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 23.13 step ratio : 0.2983 ESS R:  1.000 S:  1.000 Class Size: 1.1% (Average: 7.5%)
   -- Class  1 -- lr: 0.20 eps: 23.13 step ratio : 0.3278 ESS R:  1.000 S:  1.000 Class Size: 1.7% (Average: 28.1%)
   -- Class  2 -- lr: 0.20 eps: 23.13 step ratio : 0.6616 ESS R:  1.000 S:  1.000 Class Size: 5.1% (Average: 18.8%)
   -- Class  3 -- lr: 0.20 eps: 23.13 step ratio : 0.6280 ESS R:  1.000 S:  1.000 Class Size: 2.6% (Average: 5.3%)
   -- Class  4 -- lr: 0.20 eps: 23.13 step ratio : 0.7006 ESS R:  1.000 S:  1.000 Class Size: 4.5% (Average: 6.6%)
   -- Class  5 -- lr: 0.20 eps: 23.13 step ratio : 0.6756 ESS R:  1.000 S:  1.000 Class Size: 4.7% (Average: 10.0%)
   -- Class  6 -- lr: 0.20 eps: 23.13 step ratio : 0.6480 ESS R:  1.000 S:  1.000 Class Size: 4.1% (Average: 9.2%)
   -- Class  7 -- lr: 0.20 eps: 23.13 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 13.6% (Average: 3.1%)
   -- Class  8 -- lr: 0.20 eps: 23.13 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 29.9% (Average: 5.7%)
   -- Class  9 -- lr: 0.20 eps: 23.13 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 32.6% (Average: 5.8%)

  Done iteration 00631 of 01290 in 25.808s. Total time 17362.0s. Est time remaining 19660.7s.
----------- Iteration   632 (epoch 1.480).  radwn 27.28  resolution 11.09A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 45.29 step ratio : 1.0388 ESS R:  1.000 S:  1.000 Class Size: 2.7% (Average: 7.5%)
   -- Class  1 -- lr: 0.20 eps: 45.29 step ratio : 0.8752 ESS R:  1.000 S:  1.000 Class Size: 2.6% (Average: 28.0%)
   -- Class  2 -- lr: 0.20 eps: 45.29 step ratio : 0.6222 ESS R:  1.000 S:  1.000 Class Size: 1.1% (Average: 18.7%)
   -- Class  3 -- lr: 0.20 eps: 45.29 step ratio : 1.0295 ESS R:  1.000 S:  1.000 Class Size: 2.1% (Average: 5.3%)
   -- Class  4 -- lr: 0.20 eps: 45.29 step ratio : 0.4112 ESS R:  1.000 S:  1.000 Class Size: 0.3% (Average: 6.6%)
   -- Class  5 -- lr: 0.20 eps: 45.29 step ratio : 0.5685 ESS R:  1.000 S:  1.000 Class Size: 1.2% (Average: 10.0%)
   -- Class  6 -- lr: 0.20 eps: 45.29 step ratio : 0.7306 ESS R:  1.000 S:  1.000 Class Size: 1.5% (Average: 9.2%)
   -- Class  7 -- lr: 0.20 eps: 45.29 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 13.7% (Average: 3.1%)
   -- Class  8 -- lr: 0.20 eps: 45.29 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 36.3% (Average: 5.8%)
   -- Class  9 -- lr: 0.20 eps: 45.29 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 38.5% (Average: 5.9%)

  Done iteration 00632 of 01290 in 26.302s. Total time 17388.3s. Est time remaining 19395.8s.
----------- Iteration   633 (epoch 1.484).  radwn 27.32  resolution 11.07A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 310.79 step ratio : 0.0093 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.4%)
   -- Class  1 -- lr: 0.20 eps: 310.79 step ratio : 0.0083 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 27.9%)
   -- Class  2 -- lr: 0.20 eps: 310.79 step ratio : 0.0107 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.7%)
   -- Class  3 -- lr: 0.20 eps: 310.79 step ratio : 0.0097 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.3%)
   -- Class  4 -- lr: 0.20 eps: 310.79 step ratio : 2.9614 ESS R:  1.000 S:  1.000 Class Size: 0.5% (Average: 6.6%)
   -- Class  5 -- lr: 0.20 eps: 310.79 step ratio : 4.1940 ESS R:  1.000 S:  1.000 Class Size: 1.0% (Average: 9.9%)
   -- Class  6 -- lr: 0.20 eps: 310.79 step ratio : 1.1831 ESS R:  1.000 S:  1.000 Class Size: 0.1% (Average: 9.2%)
   -- Class  7 -- lr: 0.20 eps: 310.79 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 18.4% (Average: 3.1%)
   -- Class  8 -- lr: 0.20 eps: 310.79 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 44.1% (Average: 5.9%)
   -- Class  9 -- lr: 0.20 eps: 310.79 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 36.0% (Average: 6.0%)

  Done iteration 00633 of 01290 in 26.427s. Total time 17414.7s. Est time remaining 19163.3s.
----------- Iteration   634 (epoch 1.487).  radwn 27.36  resolution 11.05A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 649537.85 step ratio : 0.0250 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.4%)
   -- Class  1 -- lr: 0.20 eps: 649537.85 step ratio : 0.0040 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 27.8%)
   -- Class  2 -- lr: 0.20 eps: 649537.85 step ratio : 7.8278 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.6%)
   -- Class  3 -- lr: 0.20 eps: 649537.85 step ratio : 0.0047 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.2%)
   -- Class  4 -- lr: 0.20 eps: 649537.85 step ratio : 0.0132 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 6.6%)
   -- Class  5 -- lr: 0.20 eps: 649537.85 step ratio : 0.0134 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.9%)
   -- Class  6 -- lr: 0.20 eps: 649537.85 step ratio : 0.0108 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.1%)
   -- Class  7 -- lr: 0.20 eps: 649537.85 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 18.2% (Average: 3.2%)
   -- Class  8 -- lr: 0.20 eps: 649537.85 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 39.3% (Average: 6.0%)
   -- Class  9 -- lr: 0.20 eps: 649537.85 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 42.4% (Average: 6.1%)

  Done iteration 00634 of 01290 in 26.240s. Total time 17441.0s. Est time remaining 18939.4s.
----------- Iteration   635 (epoch 1.491).  radwn 27.40  resolution 11.04A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 100369040.01 step ratio : 6.1717 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.4%)
   -- Class  1 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0036 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 27.7%)
   -- Class  2 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0147 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.6%)
   -- Class  3 -- lr: 0.20 eps: 100369040.01 step ratio : 0.7592 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.2%)
   -- Class  4 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0063 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 6.5%)
   -- Class  5 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0064 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.9%)
   -- Class  6 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0053 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.1%)
   -- Class  7 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 15.3% (Average: 3.2%)
   -- Class  8 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 40.4% (Average: 6.1%)
   -- Class  9 -- lr: 0.20 eps: 100369040.01 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 44.3% (Average: 6.2%)

  Done iteration 00635 of 01290 in 26.136s. Total time 17467.1s. Est time remaining 18728.7s.
----------- Iteration   636 (epoch 1.494).  radwn 27.44  resolution 11.02A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 1034.24 step ratio : 0.0136 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.4%)
   -- Class  1 -- lr: 0.20 eps: 1034.24 step ratio : 7.5375 ESS R:  1.000 S:  1.000 Class Size: 0.3% (Average: 27.7%)
   -- Class  2 -- lr: 0.20 eps: 1034.24 step ratio : 0.0070 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.5%)
   -- Class  3 -- lr: 0.20 eps: 1034.24 step ratio : 0.0077 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.2%)
   -- Class  4 -- lr: 0.20 eps: 1034.24 step ratio : 0.0036 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 6.5%)
   -- Class  5 -- lr: 0.20 eps: 1034.24 step ratio : 0.0037 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.9%)
   -- Class  6 -- lr: 0.20 eps: 1034.24 step ratio : 0.0031 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.1%)
   -- Class  7 -- lr: 0.20 eps: 1034.24 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 16.7% (Average: 3.3%)
   -- Class  8 -- lr: 0.20 eps: 1034.24 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 40.3% (Average: 6.2%)
   -- Class  9 -- lr: 0.20 eps: 1034.24 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 42.7% (Average: 6.3%)

  Done iteration 00636 of 01290 in 26.430s. Total time 17493.6s. Est time remaining 18556.0s.
----------- Iteration   637 (epoch 1.498).  radwn 27.48  resolution 11.00A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0065 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.3%)
   -- Class  1 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0139 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 27.6%)
   -- Class  2 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0040 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.5%)
   -- Class  3 -- lr: 0.20 eps: 28869929805.68 step ratio : 5.7119 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.2%)
   -- Class  4 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0023 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 6.5%)
   -- Class  5 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0024 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.8%)
   -- Class  6 -- lr: 0.20 eps: 28869929805.68 step ratio : 2.1639 ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.0%)
   -- Class  7 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 14.2% (Average: 3.3%)
   -- Class  8 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 40.6% (Average: 6.3%)
   -- Class  9 -- lr: 0.20 eps: 28869929805.68 step ratio : 0.0000 ESS R:  1.000 S:  1.000 Class Size: 45.1% (Average: 6.5%)

  Done iteration 00637 of 01290 in 26.076s. Total time 17519.6s. Est time remaining 18375.0s.
----------- Iteration   638 (epoch 1.501).  radwn 27.52  resolution 10.99A  minisize  300  beta 0.00 
   -- Class  0 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 7.3%)
   -- Class  1 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 27.5%)
   -- Class  2 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 18.4%)
   -- Class  3 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 5.2%)
   -- Class  4 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 6.5%)
   -- Class  5 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.8%)
   -- Class  6 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 0.0% (Average: 9.0%)
   -- Class  7 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 15.7% (Average: 3.3%)
   -- Class  8 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 40.7% (Average: 6.4%)
   -- Class  9 -- lr: 0.20 eps:   inf step ratio :   nan ESS R:  1.000 S:  1.000 Class Size: 43.6% (Average: 6.6%)

  Done iteration 00638 of 01290 in 26.139s. Total time 17545.8s. Est time remaining 18213.7s.
----------- Iteration   639 (epoch 1.505).  radwn 27.56  resolution 10.97A  minisize  300  beta 0.00 
Traceback (most recent call last):
  File "/home/mestroupe/bin/cryosparc_beta/cryosparc-compute/sparcjob.py", line 288, in <module>
    cuda_devs = current_experiment_params['cuda_devs'])
  File "/home/mestroupe/bin/cryosparc_beta/cryosparc-compute/abinit.py", line 391, in abinit
    **search_params)
  File "/home/mestroupe/bin/cryosparc_beta/cryosparc-compute/search.py", line 359, in heuristicsearches
    doscale = doscale, ignore_dc = ignore_dc, cuda_workers = cuda_workers)
  File "/home/mestroupe/bin/cryosparc_beta/cryosparc-compute/search.py", line 245, in compute_Us
    results.append(work(arg))
  File "/home/mestroupe/bin/cryosparc_beta/cryosparc-compute/search.py", line 214, in work
    IW.load(D, C, 1.0/N_R, 1.0/N_S, 1.0,
ZeroDivisionError: float division by zero

----------------------end_dump----------------------------------

--
Mike

**Comment by mbrubake** [comment]
There are two issues here.  One is a bug, as this shouldn't cause a crash.  We are aware of it but haven't had the chance to fix it just yet.

The other issue is that in general this suggests that you're using too many classes.  However, if you really believe that this is the number of classes you need, one thing you can do is increase the "Class similarity" parameter.  This will force classes to differentiate more slowly which can prevent this behaviour. 

Finally, if you believe that you are looking for multiple similar structures (e.g., different conformations of the same complex) you may also want to consider providing an initial structure.

**Comment by alipunjani** [comment]
This problem should be fixed once we move abinitio reconstruction over the the new GPU code. This is work in progress (should also provide a decent speedup for abinitio reconstruction)

**Comment by spunjani** [comment]
Closing - stale. Please open a new issue if required.
