### ISSUE TITLE
different import star file error 

### ISSUE THREAD

**Issue by wliu8** [cryoem-uoft/cryosparc-issues#149]
Hi Cryosparc or users,

I failed to import my star file. Please refer to the message below and the attached images.  I know that this star file is fine since we used it for 3D refinement in Relion 1.4.   I don't know whey I got this "keyError: u 'star' when I imported it.  I am not sure what the exact problem is.  Is this the path issue or the star file issue?  Any suggestions are appreciated!!!   Thank you so much for your kind help!

Best,
Weili

-----------------------------------------------
Launched job 8z5n3sy4h3SFXWsPo
License is valid. 
Job Type:  visualize_dataset  Job ID:  8z5n3sy4h3SFXWsPo 
Assigned Slots: RAM:  None  GPU:  None 
Visualizing Dataset ID kqNaj4tFHKvAtkaap 
Loading Dataset ...  
---- Loading File Set. Type: star  Path: /gs/gsfs0/hpc01/apps/cryosparc/021317/run/bulk/./unxlink/p53PolII_krios3/Refine3D/run21_data.star  
Traceback (most recent call last):   File "/gs/gsfs0/hpc01/apps/cryosparc/021317/cryosparc-compute/sparcjob.py", line 105, in <module>     dataset = dataio.dataset_factory(current_dataset_params, do_cache=False, do_datasign_estimation=False)   File "/gs/gsfs0/hpc01/apps/cryosparc/021317/cryosparc-compute/dataio/__init__.py", line 18, in dataset_factory     do_cache=do_cache)   File "/gs/gsfs0/hpc01/apps/cryosparc/021317/cryosparc-compute/dataio/load.py", line 54, in filesets_into_dataset     images = extension_map[meta_type](dataset, meta_input) KeyError: u'star '

![screen shot 2017-02-24 at 4 40 17 pm](https://cloud.githubusercontent.com/assets/26014237/23322072/57919520-fab0-11e6-8d46-c440d7862449.png)

![screen shot 2017-02-24 at 4 57 42 pm](https://cloud.githubusercontent.com/assets/26014237/23322576/987f7564-fab2-11e6-9a13-ef253d385027.png)

**Comment by alipunjani** [comment]
Hi Weili,

Thanks for reporting.
It looks like you might have an extra trailing space in the path for your star file. If you put your curson in the meta data file input box on the Configure page, on the right I think you'll find an extra space at the end of the line after .star 
Removing that space should make it work.
I've added a patch that will be deployed in the next release to deal with this in case it happens again.

Ali

**Comment by wliu8** [comment]
Dear Ali,

Awesome! Thank you so much for your kind help.

Best,
Weili

On 2/28/17, alipunjani <notifications@github.com> wrote:
> Hi Weili,
>
> Thanks for reporting.
> It looks like you might have an extra trailing space in the path for your
> star file. If you put your curson in the meta data file input box on the
> Configure page, on the right I think you'll find an extra space at the end
> of the line after .star
> Removing that space should make it work.
> I've added a patch that will be deployed in the next release to deal with
> this in case it happens again.
>
> Ali
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cryoem-uoft/cryosparc-issues/issues/149#issuecomment-283182834


-- 
Wei-Li Liu, PhD
Assistant Professor
Department of Anatomy & Structural Biology
Gruss-Lipper Biophotonics Center
Albert Einstein College of Medicine
1300 Morris Park Avenue
Forchheimer 628D
Bronx, NY 10461

Email: wei-li.liu@einstein.yu.edu
         lily.w.liu@gmail.com
Phone: 718-430-2876
Cell: 510-541-2539

**Comment by alipunjani** [comment]
Any time, glad it's fixed :)
