### ISSUE TITLE
pyxbuild fails with 'reached maximum' error

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#152]
https://discuss.cryosparc.com/t/importerror-reload-count-sincint-so-reached-maximum/182

Probably need to stop using reload=True

**Comment by mbrubake** [comment]
Do we even still need sincint given the current code base?  If it's used at all it might be used in testing the GPU code but I doubt it's being used for much of anything in active code.  Maybe we should just find a way to avoid importing it for jobs.

**Comment by alipunjani** [comment]
You're probably right, I can't think of any place it's used any more

**Comment by alipunjani** [comment]
removed last sincint.pyx dependency from symmetry (made it on the fly if needed) so this shouldn't be an issue any more
