### ISSUE TITLE
Error refining a single class

### ISSUE THREAD

**Issue by alushing** [cryoem-uoft/cryosparc-issues#154]
Hello-

We are trying to refine a single class generated using an ab-initio reconstruction of a heterogeneous dataset.  We are able to refine the class against the entire dataset, but refinement fails when we attempt to use only the particles "assigned" to that class during the ab-initio run.  The refinement fails to launch with the following error:

`
Launched job ZpJJcgcnf3uoQBc59

License is valid.

Job Type:  superrefine  Job ID:  ZpJJcgcnf3uoQBc59

Assigned Slots: RAM:  [0, 1, 2]  GPU:  [0]

Starting  High-Res Refinement , Experiment ID  PH4obRK6mraaKE5nZ

Loading Dataset ... 

---- Loading File Set. Type: star Path: /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/particles_cryosparc.star

     Loaded meta data for 72009 images.

Could not find file Particles/img2x/Mdn1_I_1072_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_1701_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_1801_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_1855_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_2409_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_2624_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_2704_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_2803_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_3220_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_3475_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

Could not find file Particles/img2x/Mdn1_I_3516_2xaligned_particles.mrcs with base /home/greg/cryosparc/run/bulk/./local_fs/mnt/data1/Kapoor_lab/Mdn1/Particles, ignoring these images...

     Found raw data for 71717 images.

     Loading image data...

     Found references to 1358 unique data files.

Checking SSD cache for data files...

     Dataset image size is 256.

Autodetecting data sign, and computing DC estimate and noise level ... 

  Using light particle dark background.

  Autodetecting with 5000 images ..

    Median DC:         0.77105820179

    Mean DC:           0.723270195825

    Stdev of Mean DC:  0.0458026271044

  Estimated noise std dev: 1.00011

  Detected light particle dark background.

Loaded Dataset with 71717 items.

Normalizing Dataset ... 

  Done in 7.871s.

Windowing Dataset ... 

  Done in 0.002s.

Loading Input Results...

  Loaded structure from .cryosparc_output_dir/cryosparc_output_data/jobs/F3979KKL8x7Jnm6bs/cryosparc_exp000008_03_final.mrc

    Using structure to instantiate 1 classes.

  Loading particles for model-3 from .cryosparc_output_dir/cryosparc_output_data/jobs/F3979KKL8x7Jnm6bs/cryosparc_exp000008_final.csv

    Added 9104 unique particles at classification confidence threshold 0.90

Traceback (most recent call last):
  File "/home/greg/cryosparc/cryosparc-compute/sparcjob.py", line 289, in <module>
    training_set = dataio.SpoolingList([dataset[uid] for uid in input_keep_particle_uids])
IndexError: list index out of range
`
Note that the particles it can't find at the beginning of the run were also not found when it ran ab initio, so it should not have assigned them to any class.  

Thanks,
-Greg Alushin

**Comment by spunjani** [comment]
Closing - stale. Please open a new issue if required.
