### ISSUE TITLE
New job type to align maps to a common reference

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#181]
https://discuss.cryosparc.com/t/comparing-maps-from-different-cryosparc-runs/255

Could align ab-initio outputs to eachother, but still need this to align+compare different runs.

**Comment by alipunjani** [comment]
Stretch goals:

- [ ] Compute difference maps after alignment (i.e. align volume B to volume A then output A-B)
- [ ] Perform local alignment (with a user-provided mask)
- [ ] Try a robust matching error rather than squared error (eg. m-estimator)
- [ ] Perform a second fine-grained local alignment after the first coarse global search

**Comment by spunjani** [comment]
Done.
