### ISSUE TITLE
Reset Password redirects to wrong address

### ISSUE THREAD

**Issue by zrip** [cryoem-uoft/cryosparc-issues#184]
When attempting password reset the link in the email takes you to
http://localhost:38000/reset-password/[Some number]
Cryosparc is not neccesarily running on the computer where the email is opened (localhost). Maybe specify somewhere that this needs to be changed or figure out a clever way to know the host computer name where cryosparc is running?

**Comment by suhaildawood** [comment]
Thanks for the suggestion, we'll update this for the next release.

**Comment by spunjani** [comment]
Closed as not applicable in new version.
