### ISSUE TITLE
Refinement/Sharpen Experiment disabled 

### ISSUE THREAD

**Issue by jianSG** [cryoem-uoft/cryosparc-issues#185]
I reinstall my linux OS and everything else afterwards. I was able to load example data and complete Ab-initio Run. But both Refinement and Sharpen buttons are grey out and nowhere to find how to add these experiments to continue? Very strange, since I didn't have such issue with previous version.

![screenshot from 2017-04-06 17-01-58](https://cloud.githubusercontent.com/assets/26193140/24746248/04a02e70-1aeb-11e7-8a27-b2b85bd4105a.png)

**Comment by alipunjani** [comment]
Hi @jianSG,
Refinement and sharpening jobs both require a structure as input so you need to select the structure you want (click on the 'Structure' button underneath the image in experiment 1) and then the buttons will become available.

**Comment by jianSG** [comment]
Fantastic. Thanks a lot.
