### ISSUE TITLE
MAC address through ifconfig doesn't work on non-English systems

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#189]
Could either try to regex looking for `:`s or use MAC address straight from system:

https://gist.github.com/amitsaha/9677822
And check the `type` file to see if it's ethernet http://lxr.free-electrons.com/source/include/uapi/linux/if_arp.h

**Comment by mbrubake** [comment]
The easiest way is to just use the files in ```/sys/class/net/```  This should work for all modern Linux systems, although it won't work on OSX but that's probably not an issue for non-developer versions.

**Comment by mbrubake** [comment]
Ah, just realized that the gist does exactly that :)

**Comment by alipunjani** [comment]
closing for now - not bothering anyone at the moment
