### ISSUE TITLE
Issue with cache or SQL?

### ISSUE THREAD

**Issue by andreymalg** [cryoem-uoft/cryosparc-issues#192]
Trying to run a refinement job I get the following error: 
"Traceback (most recent call last):
  File "/CryoSparcInstall/cryosparc-compute/sparcjob.py", line 58, in <module>
    cache.enable(mongoaddress=MONGOADDRESS, job_id = job_id)
  File "/CryoSparcInstall/cryosparc-compute/sparc/cache.py", line 133, in enable
    cachedb = diskcache.Cache(cachedb_dir)
  File "/CryoSparcInstall/anaconda2/lib/python2.7/site-packages/diskcache/core.py", line 332, in __init__
    sql('CREATE TABLE IF NOT EXISTS Settings ('
OperationalError: unable to open database file "

I'm having trouble in identifying the underlying issue.
Thank you

**Comment by alipunjani** [comment]
Hi @andreymalg 
Can you try
`cryosparc configure cache clear force`
this should clear the SSD cache and cache database.

**Comment by alipunjani** [comment]
@andreymalg closing this for now - please report if any further issues

**Comment by andreymalg** [comment]
Turns out the scratch drive was failing. Still in process of replacing it. Will let you know if the issue still there when a new drive is in.

**Comment by sjweaver** [comment]
As a warning to others, I would not suggest running 

`cryosparc configure cache clear force`

if you have not backed up all of your /cryosparc/run/bulk/.cryosparc_output_dir/cryosparc_output_data/jobs folder.  Running it appears to have deleted my ~210 runs.  

to be fair, running this command did solve the cache issue that I was having.  So now I can definitely re-run those jobs...  

Is there a safer way to delete the cache for future reference?  

Thanks!
