### ISSUE TITLE
particle selection after Mref 

### ISSUE THREAD

**Issue by jparmache** [cryoem-uoft/cryosparc-issues#198]
Hi,

I am having an interesting issue which I am not sure whether is a feature or a problem: a dataset of 600k particles, MultiRef refinement divides the dataset into 3 subsets: 50%,24% and 26%. When selecting the 26% subset for further refinement, only 74k particles are selected. When selecting 50%, it takes 180k particles. If it is an issue, I'd like to report it. If it is a feature, could you please explain how it works ?
Best,

Jean-Paul

**Comment by alipunjani** [comment]
Hey Jean-Paul,

Good question - I suppose I would say it's a feature. What's happening is that classification scores in cryoSPARC are always probabilistic, so each image is not being strictly classified into a class until you select a class in a further experiment. There is a parameter in experiments in the 'Select Input Classes' section called the 'Class probability threshold', by default 0.9, that controls which images are actually used in an experiment. So by default only images that are 90% or more confident of being in the selected class get used.

In your case I guess the classifications remain fairly soft after the multirefinement experiment, so many images are not confidently belonging to any of the classes and don't cross the threshold. You can change that threshold to select more images including those that are less confidently classified.

Hope this helps,
Ali

**Comment by jparmache** [comment]
Hi Ali,

Thanks for the explanation, I had a feeling this parameter controlled it, but wanted to make sure. I will play around with this parameter.
Hope you're doing great,

Best,

Jean-Paul

**Comment by alipunjani** [comment]
Great :) 
Thanks, we're all doing alright here, hope you're all well too!

Ali
