### ISSUE TITLE
Local resolution estimation

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#209]
Something similar to blocres (from Bsoft, https://lsbr.niams.nih.gov/bsoft/programs/blocres.html) would be a good starting point
Could also wrap ResMap

**Comment by olibclarke** [comment]
I would suggest the blocres route rather than ResMap... ResMap systematically overestimates local resolution, it is fine for qualitative analysis but I think blocres is more robust

**Comment by spunjani** [comment]
Closed as finished!
