### ISSUE TITLE
Error During Dataset Visualization for version 4.4

### ISSUE THREAD

**Issue by tanyongzi** [cryoem-uoft/cryosparc-issues#227]
There is an error during dataset visualization for version 4.4, which prevents users from uploading. When I reverted to version 4.1, the uploading worked. Could you please look into it? Thank you!

<pre>
===========================================================

Loaded Dataset with 99203 items.

  Microscope Params: 

                   akv :  300

                    cs :  2.7

                dscale :  1.0

             imagesize :  342.4

                 psize :  1.07

                   wgh :  0.07

===========================================================

Traceback (most recent call last):
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/sparcjob.py", line 125, in <module>
    fig = plotutil.plot_dataset_images(subset, radwn=6, figscale=2, rand=False)
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/plotutil.py", line 409, in plot_dataset_images
    rD *= img.dataset.prepare_real_window.max()
AttributeError: 'float' object has no attribute 'max'
</pre>

**Comment by alipunjani** [comment]
Fixed in v0.5.0 
Thanks!
