### ISSUE TITLE
Creation of admin users doesn't work

### ISSUE THREAD

**Issue by YacobGomez** [cryoem-uoft/cryosparc-issues#236]
Hi,
I am trying to use the feature "add user" from the administrators menu to add a new Admin user, but it doesn't work.
After typing the information of the user, the checkbox to introduce the information in the system is always a "cross" "X" to cancel the action, being impossible to actually add any user, no matter the information that you have typed.
Actually, it doesn't work for adding a regular user either.
I tried both Chrome and Firefox in Ubuntu 14.04 and Windows 7.

Yacob
![screenshot1](https://user-images.githubusercontent.com/31222042/29535673-c713d6a6-8688-11e7-84f6-1a9a2b5ccf21.png)
![screenshot2](https://user-images.githubusercontent.com/31222042/29535675-c71577fe-8688-11e7-99e8-e7d442aa16e4.png)

**Comment by spunjani** [comment]
Closed as not applicable in new version.
