### ISSUE TITLE
Queue halted by deleted pending jobs

### ISSUE THREAD

**Issue by AndyPurk** [cryoem-uoft/cryosparc-issues#237]
Dear Cryosparc developers,

I have a machine where the queue is stalled. User(s) have deleted jobs from the queue before they had launched and so there are jobs which appear to be queue, but can't be accessed any more. 

Attached is a screen shot showing the issue, the are 9 jobs shown as queued at the top of the page, but only three in the list. As you can see, there are no experiments running. Job 143 was the last to successfully run.

Is there any way to empty the queue of these phantom jobs, or to reset the installation without losing the information about the completed jobs.

![sblinux3_cryosparc_larger](https://user-images.githubusercontent.com/25611426/29620266-5f1c0288-8815-11e7-8d2b-b5e7a578dff5.png)

Many thanks,

Andrew Purkiss

**Comment by zrip** [comment]
I have also seen this problem, if you do a quick 

`cryosparc stop`
then
`cryosparc start`

it should advance the queue in this situation. May need to be done a few times depending on how many stalled jobs you had.

**Comment by AndyPurk** [comment]
I'd already tried that, the queue remains at nine jobs, with six remaining invisible and three listed.

**Comment by alipunjani** [comment]
Were the jobs deleted by clicking the red 'x' on the experiments page? Or by running a disk cleanup job?

**Comment by alipunjani** [comment]
For now, to remove all jobs from the queue (but keep all the experiments etc):

From within the cryosparc installation directory:
```
eval $(cryosparc env)
source config.sh
mongo localhost:$CRYOSPARC_MONGO_PORT
```
Now in the database shell:
```
use meteor
db.jobs.update({status:"queued"}, {$set:{status:"killed"}})
exit
```

**Comment by AndyPurk** [comment]
I believe all the jobs were deleted by clicking the red 'X'. I certainly didn't run a disk clean up for my test job that is 'invisible'.

Thanks,

Andrew



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by AndyPurk** [comment]
Thanks, I'll give that a try.

Regards,

Andrew



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by alipunjani** [comment]
Hi @AndyPurk, did the above lines work?

**Comment by AndyPurk** [comment]
Hi @alipunjani, yes the fix worked. 

The db.jobs.update({status:"queued"}, {$set:{status:"killed"}}) command had to be run as many times as the number of queued jobs, as it only seemed to match the one entry each time.

Thanks,

Andrew

**Comment by spunjani** [comment]
Closing as this will be fixed in new version.
