### ISSUE TITLE
Auto batchsize more than half of dataset per split

### ISSUE THREAD

**Issue by olibclarke** [cryoem-uoft/cryosparc-issues#248]
Hi,

I've noticed that during homogeneous refinement in 0.5.3, CryoSPARC is using more than half the dataset per split in early iterations. 

E.g., a refinement I ran with 32000 particles total reports an auto batchsize (per split) of 18000 particles. This didn't happen previously, and unless I'm misunderstanding something the auto-batchsize (per split) should be the number of particles in each half-set for that refinement.

Is this a bug, or has the reporting changed somehow? Or is there something else I'm missing?

Cheers
Oli

**Comment by alipunjani** [comment]
Hey @olibclarke, nothing has changed in homogeneous refinement for several versions - the Auto batch size that is reported is only the batch size that would be ideal to use for that iteration, if there are less particles in either half, only that many are actually used in each half. The lines that begin "Processed XXX images in XXs" report the actual number of particles used (sum of both halfs)

**Comment by olibclarke** [comment]
Ah got it, sorry @alipunjani, my mistake then.
