### ISSUE TITLE
anaconda2 fail during install

### ISSUE THREAD

**Issue by hansenbry** [cryoem-uoft/cryosparc-issues#259]
Hi I'm trying to install cryosparc on a CentOs 7.4 system and I'm getting the below error when trying to install the python library.  I've chosen in the install to have everything install into the cryosparc directory.  Let me know what other information would be helpful for trouble shooting.  Below is the last error message in the terminal.

Package plan for installation in environment /home/hansenbry/cryosparc/anaconda2:

The following NEW packages will be INSTALLED:

    fftw:   3.3.4-0          richli
    pyfftw: 0.9.2-np19py27_0 richli

Traceback (most recent call last):
  File "/home/hansenbry/cryosparc/anaconda2/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by spunjani** [comment]
Closing as this will be fixed in new version.
