### ISSUE TITLE
conflict when installing

### ISSUE THREAD

**Issue by JuhaHuiskonen** [cryoem-uoft/cryosparc-issues#261]
Hello, I am getting this error when installing:

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pandas=0.18.1
  - pyfftw=0.9.2
Use "conda info <package>" to see the dependencies for each package.

**Comment by alipunjani** [comment]
Hi Juha,
This is now fixed in v0.6.5. If you just try installing again, you'll get the latest version.
Ali
