### ISSUE TITLE
trouble logging into cryosparc account.

### ISSUE THREAD

**Issue by sdhindwal** [cryoem-uoft/cryosparc-issues#274]
Dear Cryosparc team,

I am having trouble logging into my cryosparc account.

I enter my username and password but the site complains that password is incorrect. I ask for the reset password, but the link which I get on my mail is not working. It says "Site can not be reached".

I have trying resetting the password using the terminal, using:
cryosparc resetpassword <user email> <new password>

It says attempting password reset, but still I am not able to reset my password.
Please help.

Thanks a lot.

**Comment by spunjani** [comment]
Closing as flagged & answered on the discussion forum.
