### ISSUE TITLE
Display mask on first use in Homogeneous Refinement

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#28]
I am playing with the tightness of masks in refinement (trying masks that exclude low-density amphipol; many will try things like this) by changing the the initial resolution in refinement, the threshold for masking, and the near and far 1->0 transition in the mask. The mask is not shown in the 0th iteration (when the low-pass filtered reference map is shown) meaning th effects of different mask setting can't be seen until a round of alignment is complete. Would be better if mask is shown immediately with LP-filtered reference.

**Comment by mbrubake** [comment]
The mask used in the first iteration is now displayed at the beginning of refinement.  Note that in general it's not terribly interesting unless you're using a custom mask or you've adjusted refine_dynamic_mask_start_res.  As Ali mentioned the better long term solution is better tools for masks.
