### ISSUE TITLE
Add an experiment type that is just masking, FSC, and sharpening

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#29]
One often wants to see the effect of different masks, and even different user set (not automatic) B-factors on map resolution and appearance, respectively (e.g. If FSC tight mask excludes a fuzzy region does mask resolution improve? Low resolution features often disappear on sharpening - can something be seen with less sharpening?). This section of code could be duplicated in a "postprocessing" experiment type (Relion nomenclature - avoid using it) so that these things can be tried without doing a full homogeneous refinement.

**Comment by spunjani** [comment]
Done.
