### ISSUE TITLE
Guinier estimation often fails

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#37]
Often the guinier estimate is -1000 and the estimated like doesn't seem to match the structure power at all - might be something to do with initialization of the WLS

**Comment by mbrubake** [comment]
@alipunjani Are you still seeing this often?  If so, do you have any datasets/experiments that it happens regularly with that I could look at?  The fix for #44 (which went in a while ago, but after this was filed) might have helped some of this.

**Comment by alipunjani** [comment]
Still seeing this often yeah, maybe 1 out of every 3 refinements, especially at medium resolutions (not usually seen once we're beyond 6A)
![image](https://cloud.githubusercontent.com/assets/2576358/21252996/2d7d351e-c329-11e6-9882-228bd8c82b3f.png)

**Comment by johnrubinstein** [comment]
Presume you remember: there's no reason for Guinier plot to be linear at worse than ~9/10 Å. I think people frequently report that Guinier plots are not as linear as theory suggests they should be. Makes sense that fitting line is most reliable for high-resolution.

**Comment by mbrubake** [comment]
@johnrubinstein Yes, it's not using any frequencies above 10Å when fitting.  I believe this is a bug in the implementation which I've tracked down.  I'm testing now but hopefully I can close this soon.

**Comment by mbrubake** [comment]
Ok, I think this should be fixed now.  If it shows up again let me know.

**Comment by alipunjani** [comment]
This seems to be happening still, much less often than before and I haven't found any pattern yet for when it does happen:
![image](https://cloud.githubusercontent.com/assets/2576358/22077264/6ee638c6-dd81-11e6-9700-c1154224ffea.png)

**Comment by mbrubake** [comment]
Ok, I know what I need to do to fix this, I'll try to get it done tonight or sometime soon.

**Comment by spunjani** [comment]
Close as stale.
