### ISSUE TITLE
Dampening of maps can occur during B-factor estimation

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#44]
It looks like the B-factor estimation determined a negative B-factor and applied a positive B-factor in the first iteration. I don't think this should happen. It's not a big factor, but still...

![screen shot 2016-03-28 at 9 46 56 am](https://cloud.githubusercontent.com/assets/17182155/14079291/90406618-f4ca-11e5-9375-ad9814c8371e.png)

**Comment by mbrubake** [comment]
I just checked the code and I think this should be fixed now assuming I'm reading things correctly.  @johnrubinstein if you are still seeing this let me know.
