### ISSUE TITLE
CentOS Installation Issue

### ISSUE THREAD

**Issue by tanyongzi** [cryoem-uoft/cryosparc-issues#62]
Dear all,

I know that CryoSPARC isn't meant for CentOS, but I have managed to almost install it successfully. The only additional step in installation is to do this: http://unix.stackexchange.com/questions/63587/how-to-install-g-4-7-2-c11-on-centos-5-x

CryoSPARC is now running in the background; however the website is not available. I tried unblocking the 38000 port but to no avail. I will keep troubleshooting, but any suggestions would be helpful. Thank you.

**Comment by alipunjani** [comment]
CentOS installation with the latest version of cryosparc has been tested and works out of the box if CUDA, git, ssh, and gcc etc are already installed via yum. However, it is critical to make sure port 38000 (cryosparc default port) is open in the CentOS firewall (that is usually enabled by default). I'll close this issue for now.

**Comment by mbrubake** [comment]
Ali, what version of CentOS did you test this on?  I think there may be differences between 7 and 6.

**Comment by alipunjani** [comment]
Good point - it was CentOS 7.

**Comment by tanyongzi** [comment]
Yup, we have CentOS 6.8 and it has alot of differences with CentOS 7.

**Comment by alipunjani** [comment]
In that case we have more work to do :)

**Comment by tanyongzi** [comment]
Apologies Ali as well for not responding - I have no idea why I am not getting any alerts on your reply. It is definitely not a port issue as we have tried opening it (it is a local machine) and nothing works.

**Comment by alipunjani** [comment]
What does `cryosparc status` report?

**Comment by tanyongzi** [comment]
It reports:

`bash-4.1$ cryosparc status
Running CryoSPARC Tool at /mnt/fast_scratch/progs/cryosparc
Current cryoSPARC version: v0.2.10


Process status:

meteor                           STOPPED   Not started
mongod                           RUNNING   pid 29657, uptime 0:00:39
webapp                           RUNNING   pid 30421, uptime 0:00:02

Config variables:

export CRYOSPARC_ROOT_DIR="/mnt/fast_scratch/progs/cryosparc"
export CRYOSPARC_BASE_PORT=38000
export CRYOSPARC_MONGO_PORT=38001
export CRYOSPARC_MASTER_HOSTNAME="semcgpu02"
export CRYOSPARC_INSTALL_TYPE=master
export CRYOSPARC_DEVELOP=false
export CRYOSPARC_SUPERVISOR_SOCK_FILE=/tmp/supervisor--5875718892256977788.sock
#export CRYOSPARC_SUPERVISOR_SOCK_FILE=/var/tmp/supervisor.sock

export CRYOSPARC_CACHE_CUSHION=1024.0
export CRYOSPARC_CUDA_DEVS="0,1,2,3"
export CRYOSPARC_RAM_SLOTS="32"

`

It seems Meteor is the problem.

**Comment by tanyongzi** [comment]
`---------------------
 __ __  __ ___    ___
(_ |__)|__) | |\ | |
__)|   |  \_|_| \| |

---------------------
    VERSION 0.1.1
---------------------
Kadira: completed instrumenting the app
/mnt/fast_scratch/progs/cryosparc/cryosparc-webapp/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /mnt/fast_scratch/progs/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/extension_binary/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/mnt/fast_scratch/progs/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/fast_scratch/progs/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
`

**Comment by tanyongzi** [comment]
Fixed it!

- What is missing from CentOS 6.8's libstdc++.so.6 is GLIBCXX_3.4.15. Technically, CentOS 6.8 has no upgrades to GLIBCXX_3.4.15
- The workaround is that I have installed Chrome, and Chrome has its own libstdc++.so.6. That libstdc++.so.6 has up to GLIBCXX_3.4.22. Hence I symbolically linked this libstdc++.so.6 to the system's libstdc++.so.6.

o	sudo ln -s /opt/google/chrome/lib/libstdc++.so.6 /usr/lib64/
o	strings /usr/lib/ libstdc++.so.6 | grep GLIBC

**Comment by alipunjani** [comment]
Awesome! glad you managed to figure it out. 

It looks like the issue was with Node.JS rather than our own cryosparc code. I tried looking briefly for a Node 4.5.0 (version we use) binary for CentOS 6 but couldn't find anything, so for now your fix is the best way to do it. I'll close this issue for now. Thanks!

**Comment by yarikson** [comment]
Had ~same problem now (cryosparc installed and running, but localhost:38000 does not connect).
Problem indeed seemed in the missing GLIBCXX_3.4.15 - as judged by looking into cryosparc/run/meteor.stdout
The default RedHat 6.8 libstdc++ had only GLIBCXX_3.4.13 - as judged by:
`strings /usr/lib64/libstdc++.so.6 | grep 'GLIBCXX'`

Solved it by just pointing the 'old' RHEL link /usr/lib64/libstdcc++.so.6 to a newer version of same library from cryosparc anaconda package:
`strings /opt/EM/cryosparc/anaconda2/lib/libstdc++.so.6 | grep 'GLIBCXX'`
`ln -s /opt/EM/cryosparc/anaconda2/lib/libstdc++.so.6 /usr/lib64/`
