### ISSUE TITLE
Bulk directory browser fails if directory missing

### ISSUE THREAD

**Issue by asarnow** [cryoem-uoft/cryosparc-issues#63]
If a directory is missing (e.g. because a disk was unmounted) the bulk directory browser will stop listing after this directory is reached. That is, it will show other directories up until the missing one is encountered, and then no more will be displayed.

After the missing directory is removed from the bulk list on the command line, the program works as expected.

**Comment by alipunjani** [comment]
Fixed in 0.2.26
