### ISSUE TITLE
Reading in metadata files fails and crashes jobs

### ISSUE THREAD

**Issue by eugenepalovcak** [cryoem-uoft/cryosparc-issues#65]
I'm trying to do an _ab initio_ reconstruction to sub-classify a set of particles identified in a previous _ab initio_ run. I need to specify the initial class membership through the previously generated metadata file. Although the metadata file exists at the given path, it doesn't get read in successfully and the job crashes:
	
Loading Meta file from /faststorage/cryosparc/run/bulk/sparcoutput/sparcdata/jobs/kYZvDQdKhJJHd35kC/cryosparc_exp000027_final.csv ...
Traceback (most recent call last):
  File "/faststorage/cryosparc/cryosparc-compute/sparcjob.py", line 153, in <module>
    meta_dict = dataio.metafile.read_file_into_dict(meta_file, 'images')
  File "/faststorage/cryosparc/cryosparc-compute/dataio/metafile.py", line 375, in read_file_into_dict
    file_meta_data, tables = read_meta_file(input_path);
  File "/faststorage/cryosparc/cryosparc-compute/dataio/metafile.py", line 99, in read_meta_file
    inputdata.seek(tableend)
ValueError: I/O operation on closed file

**Comment by alipunjani** [comment]
Hey Eugene,

Hey Eugene,

This is a bug with the latest version of the Python 'pandas' package. If you can downgrade that will fix it:

$ conda install pandas=0.18.1

I will fix it properly in the code asap.

**Comment by eugenepalovcak** [comment]
Your solution worked perfectly, I get no error now.

**Comment by alipunjani** [comment]
Great! I'll leave this issue open until it's completely fixed.

**Comment by alipunjani** [comment]
Package versions are now fixed in the installer.
