### ISSUE TITLE
Sharpening tool with large b-factors outputs all NaNs

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#67]
Seen with boxsize 448 at least

**Comment by mbrubake** [comment]
We're probably overflowing the exponential function at high frequencies.  It overflows with surprisingly small values in even in double precision let along single precision.  We may need to do some clever hacks with log transforms in this case.

**Comment by alipunjani** [comment]
Fixed by adding  a parameter for the max resolution for sharpening (and auto-geuessing it by default). Also switched to float64 for sharpening but the real issue was limiting the resolution with high bfactors, otherwise the envelope is > 1e100 near the edges of the box.
