### ISSUE TITLE
cryosparc throws error (immediately?) after running

### ISSUE THREAD

**Issue by ekellogg** [cryoem-uoft/cryosparc-issues#70]
I loaded my dataset successfully but upon runtime it crashes with the following traceback:

Traceback (most recent call last):
  File "/cryspark/cryosparc-deploy/cryosparc-compute/sparcjob.py", line 218, in <module>
    cuda_devs = exp_params['cuda_devs'])
  File "/cryspark/cryosparc-deploy/cryosparc-compute/abinit.py", line 280, in abinit
    rM_plot, t, R = sigproc.align_density(rM, do_shift=False)
  File "/cryspark/cryosparc-deploy/cryosparc-compute/sigproc.py", line 227, in align_density
    assert n.all(n.isfinite(mu))
AssertionError

**Comment by alipunjani** [comment]
Hi Liz, 

Thanks for filing this, can you confirm a couple details for me:
1) was this a refinement job where you supplied a reference and set the refinement symmetry to something other than C1?
2) Does the reference structure you provided look like it actually is symmetric?

The crash is happening when cryosparc is trying to automatically align the reference structure you provided to the specified symmetry axes. It most likely means cryosparc was unable to detect the symmetry. If you're okay with it, it would be helpful if you can send me the reference structure so I can reproduce the crash here and try to fix it.

Also for now, if you can manually align the reference to your specified symmetry axes in chimera, then you can restart the refinement and set the 'Do symmetry alignment' option to false (in Refinement->advanced parameters).

Thanks!
Ali

**Comment by alipunjani** [comment]
Nevermind, looks like this was an ab-initio job. I'm checking into it from here.
I'll keep you posted.

**Comment by ekellogg** [comment]
yeah, I didn't supply a reference structure, just particles. I was able to
2D classify the particles successfully in relion with no issues, so the
input star file should work.
 I am happy to supply whatever you need to troubleshoot. let me know!

**Comment by alipunjani** [comment]
Hi Liz,
Turns out the trouble was the amplitude contrast. You entered 80, which would have been correct except that I made a mistake in the label text for that field... it's not percent, it's fraction. So 80% would be 0.8. I changed that in your dataset and re-started your job.
But is 0.8 correct (is this negative stain data?) Most people use 0.07 for cryo, I believe?

**Comment by ekellogg** [comment]
Hi Ali

thanks!! yes it's negative stain data, hence the large value for amp.
contrast. you are right though, 0.07 is an appropriate number for cryo.
thank you for helping me to fix it!

Liz

**Comment by mbrubake** [comment]
When updating the help text for that option, it might be good to include
something like "Typical values for cryo are 0.07 and 0.8 for negative
stain" or something like that.

**Comment by johnrubinstein** [comment]
Maybe restrict values (0,1).

⁣--

**Comment by alipunjani** [comment]
Good ideas - both done. Thanks!
