### ISSUE TITLE
Error when Using 1080 vs 980 Ti

### ISSUE THREAD

**Issue by tanyongzi** [cryoem-uoft/cryosparc-issues#71]
I am having this error when I try to run CryoSPARC Ab Initio:

`ExecError: error invoking 'nvcc --preprocess -arch sm_61 -I/home/cryosparc/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda /tmp/tmpyzi0zK.cu --compiler-options -P': [Errno 2] No such file or directory`

This occurs when I try to use my 1080 to run. When I switch over to using the 980 Ti to run, it proceeds fine. I have installed Cuda 8 on my workstation (tricky as it broke alot of things) as well.

**Comment by alipunjani** [comment]
Hi Yong Zi,

I believe to fix this what you'll have to do is switch over completely to CUDA 8. CryoSPARC can only use one CUDA version at a time, and when it was installed, it was compiled against CUDA 7.5 (assuming that's what you had for your 980). 

Steps to fix:
1) Ensure that your PATH and LD_LIBRARY_PATH point to CUDA 8. To do this, find CUDA 8 (usually /usr/local/cuda-8.0) and then edit your ~/.bashrc to prepend both the cuda-8.0/bin to PATH and cuda-8.0/lib64 for LD_LIBRARY_PATH. You may have to delete lines that cryosparc added when it was installed (those point to your older CUDA version)
2) restart your shell/terminal, then make sure CUDA8 is in the PATH `echo $PATH` and that nvcc is there `which nvcc`
2) `cryosparc stop` 
3) `pip uninstall pycuda`
4) `pip install --no-cache-dir pycuda`
5) `cryosparc start`

Then you should be good to go. You should also just make sure which GPUs are enabled:
`cryosparc configure gpu list`
and then to enable a specific one:
`cryosparc configure gpu enable <id#>`

Hope that helps,
Ali

**Comment by alipunjani** [comment]
By the way, I'm not sure what system you're running but if it's ubuntu, the simplest way is to use 16.04 with CUDA8 (everything works out of the box).

**Comment by tanyongzi** [comment]
Thanks, I will try that! I actually re-installed cryosparc after I installed cuda8 because I thought this might happen. Let's see if this works!

**Comment by tanyongzi** [comment]
Oops, there is a different error:

ImportError: libcurand.so.8.0: cannot open shared object file: No such file or directory

**Comment by alipunjani** [comment]
This usually means the LD_LIBRARY_PATH was not set correctly (/usr/local/cuda-8.0/lib64 by default)

**Comment by tanyongzi** [comment]
Thanks Ali! Case closed, it works now on both 980 Ti and 1080. Thanks!
