### ISSUE TITLE
Clicking update should schedule the update for after the current jobs finish

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#72]
So that people will actually immediately click update and not loose the state of the queue/have to kill running jobs.
Would have to test what happens on startup when the queue is not empty.

**Comment by mbrubake** [comment]
To avoid the queue issue we could lock down any further changes once the update button was clicked.  I.E., cryoSPARC would become read-only at that point and no one could create/modify/queue experiments or create/modify datasets until the current jobs finished or were killed and the update was performed.
