### ISSUE TITLE
Small Issue: Restart

### ISSUE THREAD

**Issue by tanyongzi** [cryoem-uoft/cryosparc-issues#73]
Small issue, using cryosparc restart someone does not restart cryosparc properly. When I disabled a GPU, and did cryosparc restart twice, the GPU is still enabled. When I do cryosparc stop, then cryosparc start, the GPU becomes disable.

**Comment by alipunjani** [comment]
You're right. For now I've removed the restart option completely, so users can just do `stop` then `start`.
