### ISSUE TITLE
New Dataset issue (IndexError: list index out of range)

### ISSUE THREAD

**Issue by kylelmorris** [cryoem-uoft/cryosparc-issues#74]
I am consistently getting the following import error. Happens regardless of whether I point to the original location of the *.star and *.mrcs in the original relion directory structure or create a single new stack with associated star file. Not a python person, guessing this is an error in counting columns in the star file but could someone point me to where this error precisely arises from?

Thanks!

Launched job bvfWJP6DB7Q8ndAai
License is valid.
Job Type:  visualize_dataset  Job ID:  bvfWJP6DB7Q8ndAai
Assigned Slots: RAM:  None  GPU:  None
Visualizing Dataset ID fZx4etJcRK5Smg9bG
Loading Dataset ... 
---- Loading File Set. Type: star Path: /home/kmorris/cryosparc/run/bulk/./sdd1/data/Qingtao/titan_K2_AP1_dataset/relion/autopick_all_bin4.star
Traceback (most recent call last):
  File "/home/kmorris/cryosparc/cryosparc-compute/sparcjob.py", line 78, in <module>
    dataset = dataio.dataset_factory(dataset_params, do_cache=False, do_datasign_estimation=False)
  File "/home/kmorris/cryosparc/cryosparc-compute/dataio/__init__.py", line 22, in dataset_factory
    do_cache=do_cache)
  File "/home/kmorris/cryosparc/cryosparc-compute/dataio/load.py", line 44, in fileset_into_dataset
    images = extension_map[meta_type](dataset, meta_input)
  File "/home/kmorris/cryosparc/cryosparc-compute/dataio/load.py", line 206, in star_into_dataset
    data = n.loadtxt(fname, dtype=str, skiprows = numhdr, usecols=range(len(labels)))
  File "/home/kmorris/cryosparc/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 806, in loadtxt
    vals = [vals[i] for i in usecols]
IndexError: list index out of range

**Comment by alipunjani** [comment]
Hey Kyle, you're right this is related to missing columns in some rows in a star file. The likely culprit is that you have multiple header rows in your star file (common if you concatenated star files) and right now cryosparc assumes only one header. We'll fix that soon but for now if you remove those extra headers it should work. Let me know if it does

**Comment by kylelmorris** [comment]
Hey Ali, thanks for this. Couldn't ind the issue when I pointed to the raw data, star looks ok, no duplicate headers, this star file didn't come from concatenation. Did find in the single stack star file I made that there was a stray line at the end which when deleted made it possible to import into cryoSPARC. Makes sense. Onwards to find what's up in the original star files. Thanks

**Comment by alipunjani** [comment]
Hmm.. in that case can you send me the star file that cryosparc is having trouble with? reading of inputs needs to be solidified a fair bit.

**Comment by kylelmorris** [comment]
I got relion to make the star file again by reextracting the particles and everything was fine. Sorry, in the process I lost the naughty star file.... If it happens again I'll send over, thanks for your help Ali!

**Comment by mbrubake** [comment]
Closing for now, if the issue reemerges we can reopen.
