### ISSUE TITLE
error uploading dataset to cryosparc

### ISSUE THREAD

**Issue by ekellogg** [cryoem-uoft/cryosparc-issues#76]
Hi Ali et al.

I tried uploading a new dataset to cryosparc, however I get this error which implies that it cannot find my files. However, I checked that the filesystem I need to access is mounted on  the machine hosting cryo-sparc, and the file I tried to upload is definitely there. I think a screenshot of the error would be most informative.

Any advice on what the issue is and how to fix it would be much appreciated. 
[cryo-sparc-error.pdf](https://github.com/cryoem-uoft/cryosparc-issues/files/595840/cryo-sparc-error.pdf)

**Comment by alipunjani** [comment]
Hi Liz,

Did you manually enter a path to your data files, or did you use the File Browser in cryosparc? If you use the file browser and locate your files, everything will work I think. (On your cryosparc machine, I believe that there should be a `home` folder listed in the file browser where your home dir will be found)

What's happening is that cryosparc expects your data to be somewhere in the `bulk` storage directories that it knows about, but you've provided a path that isn't in the bulk directories. Cryosparc internally keeps a list of places in the file system where files can be loaded from (the point of this design is to support being able to load remotely mounted/network accessible data without having to copy to the cryosparc machine manually). This list can be modified by using the cryosparc command line tool `cryosparc configure bulk list` or `cryosparc configure bulk add <path>`. But in your case, `/home/` is already in the bulk list, so you can directly browse to your `/home/ekellog` in the file browser. 

Let me know if that works. I'm hoping to make this all simpler in a future update, but there are some technical reasons right now for why we need data that's being loaded to be inside the cryosparc bulk directories. 

Thanks,
Ali

Internal note: we should automatically detect when a path is entered that isn't in run/bulk but is inside a known bulk directory, and automatically figure out the path to avoid this error in most cases.

**Comment by ekellogg** [comment]
right.. when i tried to find my directory using the file browser I could
not even find my own home directory (i.e. ekellogg). Is there some issue
with our configuration? How do I get cryosparc to see my home directory?
using the same command you mentioned?

**Comment by alipunjani** [comment]
Ah, sorry yes this is because your network home dir setup is discover-on-list.. to make your home dir visible you need to log on to the cryosparc machine, switch to the `cryosparc` user (Abhiram has the password in case you don't know it) and then `ls /home/ekellogg` which will cause your home dir to appear. Then it should be visible in cryosparc.
