### ISSUE TITLE
CUDA failure when cryosparc started from shell other than bash

### ISSUE THREAD

**Issue by alipunjani** [cryoem-uoft/cryosparc-issues#78]
Because the ~/.bashrc has all the PATH and LD_LIBRARY_PATH vars set, if you start cryosparc from another shell, those vars won't be set and things will break.

**Comment by mbrubake** [comment]
We should ideally setup the environment in the cryosparc command.  That way we don't have to make any adjustments to the users environment.  I suspect the eman2 crash I saw on another report might have to do with switching out the python version on them.

I'm still working out how things are setup and sorted out for development with the code base now, but I can easily fix this once I'm up and running.

**Comment by mbrubake** [comment]
Actually, scratch that about the eman2 crash.  Had somehow missed that it was GPU related...

**Comment by mbrubake** [comment]
Just pushed changes which remove the need to modify the users bashrc file and hence should work fine regardless of users shell.
