### ISSUE TITLE
ERROR: No Heartbeat.....

### ISSUE THREAD

**Issue by kylelmorris** [cryoem-uoft/cryosparc-issues#79]
This happens after the FSC optimization. Any indication what's going wrong?

ERROR: No Heartbeat
This job was killed because a heartbeat was not received for 30 seconds.

I couldn't find the GPU's pulse either... :) Thanks!

**Comment by alipunjani** [comment]
Hey Kyle,
Does this happen every time, or did it only happen once?
And is that the end of the error message? There should be a printout of the job's logfile as well?
If that's not there, can you paste the logfile here? To find it:

1) look for the job_id for the crashed job. This is the alphanumeric string in the first line of output (click `show from top` to see it)
2) find the log file at cryosparc/run/sparcjobs/jobs/<job_id>/stdout

Thanks,
Ali

**Comment by kylelmorris** [comment]
Before it was doing this reproducibly. I have updated to v0.2.26 and this is running now without the error, it has reached iteration 1 and continues so I presume it's ok now.

Thanks,
Kyle

**Comment by alipunjani** [comment]
Hmm.. very strange. 
Thanks for the update! Let us know if it happens again.

**Comment by mbrubake** [comment]
Closing for now, we can reopen later if need be.
