### ISSUE TITLE
When particles not found cryosparc just 'waits'

### ISSUE THREAD

**Issue by johnrubinstein** [cryoem-uoft/cryosparc-issues#84]
In preparing a dataset I used a crappy starfile where the names of the particle stacks in the starfile did not match the names of the particle stacks in the specified directory. On launching visualization of the dataset CryoSPARC should give a 'file not found' type error in this situation but just sits quietly looking until the user launches the visualizer set up differently.

**Comment by alipunjani** [comment]
Hey John,
This was fixed in the latest version but unfortunately there was another bug that Zev found in that version so he went back to the second last release for now.

**Comment by alipunjani** [comment]
This is done in 0.2.31
