### ISSUE TITLE
Improve interface when browsing previous results

### ISSUE THREAD

**Issue by mbrubake** [cryoem-uoft/cryosparc-issues#90]
The Previous Results dialog is really useful but could be made a bit better.  Below is a list of small improvements that could be made.  I expect some of them may be harder than is worth doing right now, but just in case.  I may also come back and add some more here later.

- [ ] Experiment names should include the dataset name if there is one.  Right now it is, e.g., "#<exp num>: <exp name>".  I propose using "#<exp num>: <dataset name> - <exp name>"  Even better would be able to have something heirarchical where you first selected the dataset you wanted and then got a list of all experiments with that dataset.
- [ ] Results lists should be filtered by type.  E.G., if looking for an initial structure, should only show MRC files.
- [ ] Once a previous result is selected, it would be helpful if the box more clearly indicated what experiment the result was selected from.  Right now it simply displays the full path which uses the hash ID for the experiment, making it hard to check which result was used.
- [ ] Selecting a result or a file in the bulk directory should just be a click on the file, not using the check box on the right.  Alternatively, put the check box on the left, directly beside the file name.

**Comment by alipunjani** [comment]
Good suggestions. The result selector definitely needs a revamp, it's pretty near useless at the moment I find.

**Comment by mbrubake** [comment]
I wouldn't go that far, I think it's actually very useful even in its current state.  A few small tweaks would go a long way to making it even more useful and slick.
