### ISSUE TITLE
Support phase plates directly in the CTF

### ISSUE THREAD

**Issue by mbrubake** [cryoem-uoft/cryosparc-issues#92]

**Comment by mbrubake** [comment]
FYI, this is now mostly done in the feature/phase_plate_ctf branch.  Just need to test it a little and it should be ready to merge for wider testing with real data.

**Comment by mbrubake** [comment]
Preliminary support has been merged and should show up in the next release.  It still needs some testing with an actual dataset though.  Currently only STAR files are supported and must contain a rlnPhaseShift parameter in degrees.  Will open a new issue to add support for phase plates from PAR files.

@alipunjani Do we have any datasets already downloaded with a suitable STAR file (ie, not with fudged CTF parameters)?

**Comment by alipunjani** [comment]
Great, awesome. Yes we have a dataset from Yong Zi that has the original star file, I'll forward you the email (he uploaded to cryoem.cs)

**Comment by alipunjani** [comment]
Oh actually he sent it to you already

**Comment by mbrubake** [comment]
Oh right, of course.  I'll take a look at that ASAP.
